{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-22T17:30:00.000+0000",
      "latitude": 50.798622667022286,
      "estimatedRestoration": "2021-12-22T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG1582'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG1582",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.79926,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.13947
            },
            {
              "py/object": "Point",
              "latitude": 50.79863,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.13935
            },
            {
              "py/object": "Point",
              "latitude": 50.79803,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.1379
            },
            {
              "py/object": "Point",
              "latitude": 50.79885,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.13775
            },
            {
              "py/object": "Point",
              "latitude": 50.79926,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.13947
            }
          ],
          "subCodes": [
            "PO12 4TQ",
            "PO12 4TT",
            "PO12 4UH",
            "PO12 4UU",
            "PO12 4UZ"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG1582",
      "engineerOnSiteTime": "2021-12-22T13:45:00.000+0000",
      "name": "PO12 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO12 4TQ",
        "PO12 4TT",
        "PO12 4UH",
        "PO12 4UU",
        "PO12 4UX",
        "PO12 4UZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.13947,
              50.79926
            ],
            [
              -1.13935,
              50.79863
            ],
            [
              -1.1379,
              50.79803
            ],
            [
              -1.13775,
              50.79885
            ],
            [
              -1.13947,
              50.79926
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "d39f53ea-6278-4e69-bf45-d6199d7d0cc4",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.1384586001308938,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "Messages": [
        {
          "py/object": "Message",
          "senderName": "tobias.sell@sse.com",
          "senderUserId": "44833855-d575-41a0-92f7-7cd8a3b8dabd",
          "text": "we aim to restore power by 03:00.",
          "UUID": "d5ee43eb-9fb0-46cc-a0ce-e332f2a98d1d",
          "py/class": "http://opengrid.com/givr/1.0#//Message",
          "sentDateTime": "2021-12-22T22:30:28.332+0000"
        }
      ],
      "loggedAt": "2021-12-22T17:48:00.000+0000",
      "latitude": 50.861566379499926,
      "estimatedRestoration": "2021-12-23T03:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG1771'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG1771",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.86138,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.21216
            },
            {
              "py/object": "Point",
              "latitude": 50.86171,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.21174
            },
            {
              "py/object": "Point",
              "latitude": 50.86187,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.21063
            },
            {
              "py/object": "Point",
              "latitude": 50.86125,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.21116
            },
            {
              "py/object": "Point",
              "latitude": 50.86138,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.21216
            }
          ],
          "subCodes": [
            "PO15 6LD",
            "PO15 6LX",
            "PO15 6NE",
            "PO15 6TA"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG1771",
      "engineerOnSiteTime": "2021-12-22T18:30:00.000+0000",
      "name": "PO15 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO15 6LD",
        "PO15 6LX",
        "PO15 6NE",
        "PO15 6TA"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.21216,
              50.86138
            ],
            [
              -1.21174,
              50.86171
            ],
            [
              -1.21063,
              50.86187
            ],
            [
              -1.21116,
              50.86125
            ],
            [
              -1.21216,
              50.86138
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2021-12-22T18:30:00.000+0000",
      "UUID": "af16e318-0975-41a9-b5dc-e3f3337775ac",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.2115122079628824,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "Messages": [
        {
          "py/object": "Message",
          "senderName": "tobias.sell@sse.com",
          "senderUserId": "44833855-d575-41a0-92f7-7cd8a3b8dabd",
          "text": "we aim to restore power by 00:00.",
          "UUID": "2b379ea7-71bf-4dc6-a54c-39c72329c41c",
          "py/class": "http://opengrid.com/givr/1.0#//Message",
          "sentDateTime": "2021-12-22T22:33:27.415+0000"
        }
      ],
      "loggedAt": "2021-12-22T22:02:00.000+0000",
      "latitude": 50.78381504668424,
      "estimatedRestoration": "2021-12-22T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG1838'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG1838",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.77837,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.3229
            },
            {
              "py/object": "Point",
              "latitude": 50.784,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.32251
            },
            {
              "py/object": "Point",
              "latitude": 50.79185,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.31473
            },
            {
              "py/object": "Point",
              "latitude": 50.78076,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.31001
            },
            {
              "py/object": "Point",
              "latitude": 50.77837,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.3229
            }
          ],
          "subCodes": [
            "DT2 7LP",
            "DT2 7LR",
            "DT2 7LT",
            "DT2 7LU",
            "DT2 7LX",
            "DT2 7LY",
            "DT2 7LZ",
            "DT2 7NA",
            "DT2 7NB",
            "DT2 7ND",
            "DT2 7NE",
            "DT2 7SB"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG1838",
      "name": "DT2 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT2 7LP",
        "DT2 7LR",
        "DT2 7LT",
        "DT2 7LU",
        "DT2 7LX",
        "DT2 7LY",
        "DT2 7LZ",
        "DT2 7NA",
        "DT2 7NB",
        "DT2 7ND",
        "DT2 7NE",
        "DT2 7SB"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -2.3229,
              50.77837
            ],
            [
              -2.32251,
              50.784
            ],
            [
              -2.31473,
              50.79185
            ],
            [
              -2.31001,
              50.78076
            ],
            [
              -2.3229,
              50.77837
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "77a6f166-6b9b-4513-9a92-42b2b753e983",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.3184151354068216,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-22T18:44:00.000+0000",
      "latitude": 57.22229364071028,
      "estimatedRestoration": "2021-12-22T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG1789'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG1789",
      "reference": "JG1789",
      "name": "AB33 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "AB33 8HL"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.7090675918274707,
          57.22229364071028
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2021-12-22T19:45:00.000+0000",
      "UUID": "f274a4d0-6c18-4f94-a906-76a3c5324c1c",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.7090675918274707,
      "resolved": false
    }
  ]
}
