{
  "Faults": [
    {
      "latitude": 51.78170576895659,
      "type": "LV",
      "reference": "NE3439",
      "etaUpdate": true,
      "engineerOnSiteTime": "2024-01-13T03:40:00.000+0000",
      "affectedCustomerCount": 28,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "0841181a-abea-40ee-a1df-36aaaa72fba9",
      "minLongitude": -1.514,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.5100984929253918,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2024-01-13T01:01:00.000+0000",
      "estimatedRestoration": "2024-01-13T17:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'NE3439'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/NE3439",
      "maxLongitude": -1.5056,
      "minLatitude": 51.7797,
      "name": "OX28 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "OX28 5FA",
        "OX28 5FB",
        "OX28 5FD",
        "OX28 5FE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.514,
              51.7843
            ],
            [
              -1.5056,
              51.7843
            ],
            [
              -1.5056,
              51.7797
            ],
            [
              -1.514,
              51.7797
            ],
            [
              -1.514,
              51.7843
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2024-01-13T03:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.7843,
      "etrUpdate": true
    },
    {
      "latitude": 50.78963165765416,
      "type": "LV",
      "reference": "NE3692",
      "etaUpdate": true,
      "engineerOnSiteTime": "2024-01-13T09:30:00.000+0000",
      "affectedCustomerCount": 43,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "b62e6dff-7b72-49fa-8abc-f929eb8a4b89",
      "minLongitude": -0.6578,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6539448366638293,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2024-01-13T07:31:00.000+0000",
      "estimatedRestoration": "2024-01-13T19:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'NE3692'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/NE3692",
      "maxLongitude": -0.6386,
      "minLatitude": 50.7862,
      "name": "PO22 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO22 7AF",
        "PO22 7AZ",
        "PO22 7BX",
        "PO22 7DA",
        "PO22 7DF",
        "PO22 7DP",
        "PO22 7DY",
        "PO22 7DZ",
        "PO22 7NS",
        "PO22 7NT",
        "PO22 7NU",
        "PO22 7NX",
        "PO22 7NY",
        "PO22 7NZ",
        "PO22 7PD",
        "PO22 8NJ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.6578,
              50.8035
            ],
            [
              -0.6386,
              50.8035
            ],
            [
              -0.6386,
              50.7862
            ],
            [
              -0.6578,
              50.7862
            ],
            [
              -0.6578,
              50.8035
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2024-01-13T09:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8035,
      "etrUpdate": true
    },
    {
      "latitude": 51.0173655420112,
      "type": "HV",
      "reference": "NE3802",
      "etaUpdate": true,
      "affectedCustomerCount": 12,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "7f6dd1a0-2449-427d-9651-b1c8c20f0319",
      "minLongitude": -1.6193,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.626553284257097,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2024-01-13T10:12:00.000+0000",
      "estimatedRestoration": "2024-01-13T15:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'NE3802'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/NE3802",
      "maxLongitude": -1.5962,
      "minLatitude": 51.0012,
      "name": "SO51 & SP5 Areas",
      "otherUpdate": true,
      "affectedAreas": [
        "SO51 6FT",
        "SP5 2QX",
        "SP5 2QY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.6193,
              51.0082
            ],
            [
              -1.5962,
              51.0082
            ],
            [
              -1.5962,
              51.0012
            ],
            [
              -1.6193,
              51.0012
            ],
            [
              -1.6193,
              51.0082
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2024-01-13T10:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.0082,
      "etrUpdate": true
    },
    {
      "latitude": 51.13933737060317,
      "type": "HV",
      "reference": "NE3893",
      "etaUpdate": true,
      "affectedCustomerCount": 205,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "93b4899f-320a-430a-afea-d6c9697fcb2e",
      "minLongitude": -2.152,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.992531603948627,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2024-01-13T11:31:00.000+0000",
      "estimatedRestoration": "2024-01-13T15:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'NE3893'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/NE3893",
      "maxLongitude": -1.9636,
      "minLatitude": 51.1235,
      "name": "BA12 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BA12 0QD",
        "BA12 0QJ",
        "BA12 0QL",
        "BA12 0QN",
        "BA12 0QP",
        "BA12 0QQ",
        "BA12 0QR",
        "BA12 0QS",
        "BA12 0QT",
        "BA12 0QU",
        "BA12 0QW",
        "BA12 0QX",
        "BA12 0QY",
        "BA12 0QZ",
        "BA12 0RA",
        "BA12 0RD",
        "BA12 0RE",
        "BA12 0RF",
        "BA12 0RG",
        "BA12 0RH",
        "BA12 0RJ",
        "BA12 0RL",
        "BA12 0RN",
        "BA12 0RP",
        "BA12 0RQ",
        "BA12 0RS",
        "BA12 0RT",
        "BA12 0RU",
        "BA12 0RW",
        "BA12 0RY",
        "BA12 0RZ",
        "BA12 9HH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.152,
              51.2045
            ],
            [
              -1.9636,
              51.2045
            ],
            [
              -1.9636,
              51.1235
            ],
            [
              -2.152,
              51.1235
            ],
            [
              -2.152,
              51.2045
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.2045,
      "etrUpdate": true
    },
    {
      "latitude": 51.421032552683805,
      "type": "LV",
      "reference": "NC6332",
      "etaUpdate": true,
      "affectedCustomerCount": 8,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "9f384b37-3fef-486e-adaf-9e05822c44a8",
      "minLongitude": -0.955,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9539277660776782,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2024-01-13T12:50:00.000+0000",
      "estimatedRestoration": "2024-01-13T16:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'NC6332'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/NC6332",
      "maxLongitude": -0.952,
      "minLatitude": 51.4199,
      "name": "RG2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG2 8HR",
        "RG2 8HT",
        "RG2 8HU",
        "RG2 8JH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.955,
              51.4223
            ],
            [
              -0.952,
              51.4223
            ],
            [
              -0.952,
              51.4199
            ],
            [
              -0.955,
              51.4199
            ],
            [
              -0.955,
              51.4223
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4223,
      "etrUpdate": true
    },
    {
      "latitude": 56.57590919125823,
      "type": "PSI",
      "reference": "221978",
      "etaUpdate": true,
      "affectedCustomerCount": 62,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "aa3a28f4-ebcb-4621-95a4-d5542b3f0b74",
      "minLongitude": -2.7297,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.7015438755193655,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2024-01-13T09:00:00.000+0000",
      "estimatedRestoration": "2024-01-13T16:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '221978'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/221978",
      "maxLongitude": -2.644,
      "minLatitude": 56.5509,
      "name": "DD11 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DD11 2NX",
        "DD11 2QR",
        "DD11 2QZ",
        "DD11 2RB",
        "DD11 2RD",
        "DD11 2RG"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.7297,
              56.5936
            ],
            [
              -2.644,
              56.5936
            ],
            [
              -2.644,
              56.5509
            ],
            [
              -2.7297,
              56.5509
            ],
            [
              -2.7297,
              56.5936
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.5936,
      "etrUpdate": true
    },
    {
      "latitude": 56.39524486719283,
      "type": "LV",
      "reference": "NE3831",
      "etaUpdate": true,
      "affectedCustomerCount": 23,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "fc11ecc7-cf81-4ae1-a7e0-1dd3ddbccf99",
      "minLongitude": -3.4362,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.434114564747611,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2024-01-13T10:28:00.000+0000",
      "estimatedRestoration": "2024-01-13T17:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'NE3831'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/NE3831",
      "maxLongitude": -3.4318,
      "minLatitude": 56.3941,
      "name": "PH1 & PH2 Areas",
      "otherUpdate": true,
      "affectedAreas": [
        "PH1 5NU",
        "PH1 5NX",
        "PH1 5PA",
        "PH1 5QW",
        "PH2 8HN",
        "PH2 8HP",
        "PH2 8HR",
        "PH2 8HS",
        "PH2 8HT",
        "PH2 8HX",
        "PH2 8JN",
        "PH2 8NY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.4362,
              56.3967
            ],
            [
              -3.4318,
              56.3967
            ],
            [
              -3.4318,
              56.3941
            ],
            [
              -3.4362,
              56.3941
            ],
            [
              -3.4362,
              56.3967
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2024-01-13T11:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.3967,
      "etrUpdate": true
    }
  ]
}
