{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-05T15:39:00.000+0000",
      "latitude": 50.83789571453272,
      "estimatedRestoration": "2022-05-06T01:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS7262'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS7262",
      "reference": "JS7262",
      "name": "PO14 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO14 1AR"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.1837492188265426,
          50.83789571453272
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-05T16:00:00.000+0000",
      "UUID": "de27e2a7-f8e7-402b-b4a8-44bd51ddbbe5",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.1837492188265426,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-05T18:10:00.000+0000",
      "latitude": 50.91822320652006,
      "estimatedRestoration": "2022-05-06T02:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS7294'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS7294",
      "reference": "JS7294",
      "name": "SO18 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO18 4EL",
        "SO18 4EN",
        "SO18 4EP",
        "SO18 4EQ",
        "SO18 4ER",
        "SO18 4ES",
        "SO18 4ET",
        "SO18 4EU",
        "SO18 4EW",
        "SO18 4EX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.3656046088479288,
          50.91822320652006
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-05T19:30:00.000+0000",
      "UUID": "7e9281fe-a727-4050-9b29-ac8d7ecb23cf",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.3656046088479288,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-05T16:49:00.000+0000",
      "latitude": 50.94222626217263,
      "estimatedRestoration": "2022-05-05T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS7298'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS7298",
      "reference": "JS7298",
      "name": "BA20 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BA20 1BP",
        "BA20 1BU",
        "BA20 1DF",
        "BA20 1DG",
        "BA20 1DN",
        "BA20 1DQ",
        "BA20 1DW",
        "BA20 1DX",
        "BA20 1EU",
        "BA20 1EX",
        "BA20 1EY",
        "BA20 1HN",
        "BA20 1HW",
        "BA20 1HX",
        "BA20 1HY",
        "BA20 1HZ",
        "BA20 1JG",
        "BA20 1JQ",
        "BA20 1JW",
        "BA20 1LD",
        "BA20 1LE",
        "BA20 1LF",
        "BA20 1LG",
        "BA20 1LR",
        "BA20 1LS",
        "BA20 1LU",
        "BA20 1LX",
        "BA20 1LY",
        "BA20 1LZ",
        "BA20 1NE",
        "BA20 1NH",
        "BA20 1NR",
        "BA20 1NS",
        "BA20 1PN",
        "BA20 1PW",
        "BA20 1RG",
        "BA20 1RQ",
        "BA20 1TG",
        "BA20 2QL"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.632186159123244,
          50.94222626217263
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-05T17:15:00.000+0000",
      "UUID": "71c7509d-92f5-4392-8e2c-946e0d434a04",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "evChargersAffected": [
        "82995f12-658e-4bab-9f36-7b473b6dda5b",
        "13b27dc7-7df1-4c3a-94ab-9d53295c7822"
      ],
      "longitude": -2.632186159123244,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-05T17:15:00.000+0000",
      "latitude": 51.25677117082402,
      "estimatedRestoration": "2022-05-05T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS7248'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS7248",
      "reference": "JS7248",
      "engineerOnSiteTime": "2022-05-05T16:45:00.000+0000",
      "name": "RG22 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG22 6SE",
        "RG22 6SF",
        "RG22 6SG",
        "RG22 6SQ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.1267871347752911,
          51.25677117082402
        ],
        "type": "Point"
      },
      "UUID": "07cb1f2c-75e4-4130-97f3-4606e12f5e97",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.1267871347752911,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-05T19:15:00.000+0000",
      "latitude": 51.47924119083113,
      "estimatedRestoration": "2022-05-05T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS7383'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS7383",
      "reference": "JS7383",
      "name": "RG17 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG17 0HA",
        "RG17 7BS",
        "RG17 7BT",
        "RG17 7BU",
        "RG17 7BX",
        "RG17 7BY",
        "RG17 7DB",
        "RG17 7DD",
        "RG17 7DE",
        "RG17 7DF",
        "RG17 7DG",
        "RG17 7DH",
        "RG17 7DJ",
        "RG17 7DL",
        "RG17 7DQ",
        "RG17 7EF",
        "RG17 7EG",
        "RG17 7EN",
        "RG20 7DU",
        "RG20 7EZ",
        "RG20 8HF"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.4387533648787378,
          51.47924119083113
        ],
        "type": "Point"
      },
      "UUID": "fdcebae5-1d91-4d50-b637-6670bb1fa5c0",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.4387533648787378,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-05T20:16:00.000+0000",
      "latitude": 57.683982462656736,
      "estimatedRestoration": "2022-05-06T00:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS7400'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS7400",
      "reference": "JS7400",
      "name": "IV51 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV51 9UL"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -6.300267383719046,
          57.683982462656736
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-05T21:30:00.000+0000",
      "UUID": "7dc1c6c0-b587-4815-96eb-a319758e1745",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -6.300267383719046,
      "resolved": false
    }
  ]
}
