{
  "Faults": [
    {
      "latitude": 50.847786223587505,
      "type": "LV",
      "reference": "KT4867",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-07T13:36:00.000+0000",
      "affectedCustomerCount": 31,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "160ada56-ca2e-4ff2-84d7-66d85fccdb6c",
      "minLongitude": -1.1162,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.1121130236923042,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-07T12:52:00.000+0000",
      "estimatedRestoration": "2023-04-07T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT4867'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT4867",
      "maxLongitude": -1.1064,
      "minLatitude": 50.8443,
      "name": "PO6 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO6 4PT",
        "PO6 4RF",
        "PO6 4RG",
        "PO6 4RQ",
        "PO6 4RU",
        "PO6 4RY",
        "PO6 4RZ",
        "PO6 4SN",
        "PO6 4SW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.1162,
              50.8491
            ],
            [
              -1.1064,
              50.8491
            ],
            [
              -1.1064,
              50.8443
            ],
            [
              -1.1162,
              50.8443
            ],
            [
              -1.1162,
              50.8491
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-07T13:35:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8491,
      "etrUpdate": true
    },
    {
      "latitude": 51.40879508626658,
      "type": "LV",
      "reference": "KT4963",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-07T16:25:00.000+0000",
      "affectedCustomerCount": 34,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "a61bb368-beb7-4f12-b4fd-8088f07e7b39",
      "minLongitude": -1.3142,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.3127616935362794,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-07T15:47:00.000+0000",
      "estimatedRestoration": "2023-04-07T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT4963'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT4963",
      "maxLongitude": -1.3109,
      "minLatitude": 51.4071,
      "name": "RG14 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG14 1HP",
        "RG14 2AP",
        "RG14 2AS",
        "RG14 2HS"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.3142,
              51.4096
            ],
            [
              -1.3109,
              51.4096
            ],
            [
              -1.3109,
              51.4071
            ],
            [
              -1.3142,
              51.4071
            ],
            [
              -1.3142,
              51.4096
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-07T16:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4096,
      "etrUpdate": true
    },
    {
      "latitude": 50.902643258088965,
      "type": "LV",
      "reference": "KT4987",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-07T16:55:00.000+0000",
      "affectedCustomerCount": 9,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "bba5ce0c-1ab7-446a-9445-c9b41e69d9a4",
      "minLongitude": -1.0264,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0255285273345018,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-07T16:20:00.000+0000",
      "estimatedRestoration": "2023-04-08T01:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT4987'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT4987",
      "maxLongitude": -1.0234,
      "minLatitude": 50.9013,
      "name": "PO8 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO8 9UB",
        "PO8 9UD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0264,
              50.9037
            ],
            [
              -1.0234,
              50.9037
            ],
            [
              -1.0234,
              50.9013
            ],
            [
              -1.0264,
              50.9013
            ],
            [
              -1.0264,
              50.9037
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-07T17:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.9037,
      "etrUpdate": true
    },
    {
      "latitude": 51.33696910540462,
      "type": "LV",
      "reference": "KT5008",
      "etaUpdate": true,
      "affectedCustomerCount": 15,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "885ff8c6-acdb-4903-b098-5478070be5ed",
      "minLongitude": -0.8415,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8082806688624619,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-07T17:11:00.000+0000",
      "estimatedRestoration": "2023-04-07T23:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT5008'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT5008",
      "maxLongitude": -0.7915,
      "minLatitude": 51.3326,
      "name": "GU46 & GU17 Areas",
      "otherUpdate": true,
      "affectedAreas": [
        "GU17 0NW",
        "GU17 0PX",
        "GU46 7QU"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.8415,
              51.3444
            ],
            [
              -0.7915,
              51.3444
            ],
            [
              -0.7915,
              51.3326
            ],
            [
              -0.8415,
              51.3326
            ],
            [
              -0.8415,
              51.3444
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-07T18:20:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.3444,
      "etrUpdate": true
    },
    {
      "latitude": 55.83726587619118,
      "type": "LV",
      "reference": "KT4924",
      "etaUpdate": true,
      "affectedCustomerCount": 12,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "2ee7ef62-d1cd-4628-97a9-45aa4f086b0b",
      "minLongitude": -5.0577,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.056641155029329,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-07T14:45:00.000+0000",
      "estimatedRestoration": "2023-04-07T20:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT4924'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT4924",
      "maxLongitude": -5.0554,
      "minLatitude": 55.8359,
      "name": "PA20 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PA20 0AS",
        "PA20 0BZ",
        "PA20 0DD",
        "PA20 0HJ",
        "PA20 0HW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -5.0577,
              55.838
            ],
            [
              -5.0554,
              55.838
            ],
            [
              -5.0554,
              55.8359
            ],
            [
              -5.0577,
              55.8359
            ],
            [
              -5.0577,
              55.838
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-07T15:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 55.838,
      "etrUpdate": true
    },
    {
      "latitude": 56.54675362972954,
      "type": "HV",
      "reference": "KT5050",
      "etaUpdate": true,
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "11ffbbe5-d940-495f-b63c-c63bac094276",
      "minLongitude": -3.254,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.2365367436238994,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-07T18:12:00.000+0000",
      "estimatedRestoration": "2023-04-07T21:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT5050'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT5050",
      "maxLongitude": -3.2146,
      "minLatitude": 56.5403,
      "name": "PH13 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PH13 9HA"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.254,
              56.5573
            ],
            [
              -3.2146,
              56.5573
            ],
            [
              -3.2146,
              56.5403
            ],
            [
              -3.254,
              56.5403
            ],
            [
              -3.254,
              56.5573
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-07T19:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.5573,
      "etrUpdate": true
    }
  ]
}
