{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T08:00:00.000+0000",
      "latitude": 50.819114379997195,
      "estimatedRestoration": "2022-03-21T17:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '206523'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/206523",
      "reference": "206523",
      "name": "DT11 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT11 9DH"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.1515012825925037,
          50.819114379997195
        ],
        "type": "Point"
      },
      "UUID": "f011c6a7-f0bb-453e-881f-bc5e70d1db92",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.1515012825925037,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-20T14:47:00.000+0000",
      "latitude": 50.99062659958576,
      "estimatedRestoration": "2022-03-21T04:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ3844'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ3844",
      "reference": "JQ3844",
      "engineerOnSiteTime": "2022-03-20T15:30:00.000+0000",
      "name": "SO21 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO21 1EZ",
        "SO21 1JH",
        "SO21 1JQ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.276764657694998,
          50.99062659958576
        ],
        "type": "Point"
      },
      "UUID": "2174a8dc-7637-4960-977d-2a160955568b",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.276764657694998,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-20T20:42:00.000+0000",
      "latitude": 50.91942399637069,
      "estimatedRestoration": "2022-03-20T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ3978'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ3978",
      "reference": "JQ3978",
      "name": "SO14 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO14 6RF",
        "SO14 6RG",
        "SO14 6RH",
        "SO14 6RJ",
        "SO14 6RL"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.3988067303168013,
          50.91942399637069
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-20T22:15:00.000+0000",
      "UUID": "eba7edc4-9689-4270-86b2-5c0794e09182",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.3988067303168013,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-20T22:00:00.000+0000",
      "latitude": 51.28688380572081,
      "estimatedRestoration": "2022-03-21T07:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ3988'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ3988",
      "reference": "JQ3988",
      "engineerOnSiteTime": "2022-03-20T22:45:00.000+0000",
      "name": "RG24 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG24 8SB",
        "RG24 8SD",
        "RG24 8SE",
        "RG24 8SF",
        "RG24 8SG",
        "RG24 8SQ",
        "RG26 5EQ",
        "RG26 5FN"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.0558797577523809,
          51.28688380572081
        ],
        "type": "Point"
      },
      "UUID": "22f4d615-60e1-44ba-860a-18313ec2f542",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0558797577523809,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-20T22:30:00.000+0000",
      "latitude": 51.33332468823647,
      "estimatedRestoration": "2022-03-21T02:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ4005'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ4005",
      "reference": "JQ4005",
      "name": "RG26 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG25 3JY",
        "RG26 3AW",
        "RG26 3BJ",
        "RG26 3TX",
        "RG26 3TZ",
        "RG26 3UD",
        "RG26 3UF",
        "RG26 3UG"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.158119079023501,
          51.33332468823647
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-20T23:59:00.000+0000",
      "UUID": "3070f59b-9c6c-4e7a-9d4a-854ecc50a741",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.158119079023501,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-14T10:00:00.000+0000",
      "latitude": 59.11693007695559,
      "estimatedRestoration": "2022-03-21T19:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '206022'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/206022",
      "reference": "206022",
      "name": "KW17 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "KW17 2PJ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.119189129637787,
          59.11693007695559
        ],
        "type": "Point"
      },
      "UUID": "12c3f463-535e-47d1-a23a-cd851a71c99f",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.119189129637787,
      "resolved": false
    }
  ]
}
