{
  "Faults": [
    {
      "latitude": 50.91338025951612,
      "type": "LV",
      "reference": "KF3138",
      "etaUpdate": true,
      "engineerOnSiteTime": "2022-11-19T01:20:00.000+0000",
      "affectedCustomerCount": 21,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "1d70b26f-601c-49d6-a750-5ef643b9bd5d",
      "minLongitude": -1.4965,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.493434404794076,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T00:33:00.000+0000",
      "estimatedRestoration": "2022-11-19T12:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3138'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3138",
      "maxLongitude": -1.4897,
      "minLatitude": 50.9119,
      "name": "SO40 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SO40 9AD",
        "SO40 9BE",
        "SO40 9BG",
        "SO40 9DB",
        "SO40 9DD",
        "SO40 9DE",
        "SO40 9EB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.4965,
              50.9142
            ],
            [
              -1.4897,
              50.9142
            ],
            [
              -1.4897,
              50.9119
            ],
            [
              -1.4965,
              50.9119
            ],
            [
              -1.4965,
              50.9142
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-19T01:40:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.9142,
      "etrUpdate": true
    },
    {
      "latitude": 51.399947393361465,
      "type": "LV",
      "reference": "KF3153",
      "etaUpdate": true,
      "engineerOnSiteTime": "2022-11-19T06:00:00.000+0000",
      "affectedCustomerCount": 14,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "0fa64287-e6e5-4e35-a486-3d653e3f3ea7",
      "minLongitude": -0.8749,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8725703036640862,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T02:41:00.000+0000",
      "estimatedRestoration": "2022-11-19T14:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3153'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3153",
      "maxLongitude": -0.8705,
      "minLatitude": 51.3993,
      "name": "RG41 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG41 4UR",
        "RG41 4UW",
        "RG41 4YY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.8749,
              51.4007
            ],
            [
              -0.8705,
              51.4007
            ],
            [
              -0.8705,
              51.3993
            ],
            [
              -0.8749,
              51.3993
            ],
            [
              -0.8749,
              51.4007
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-19T06:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4007,
      "etrUpdate": true
    },
    {
      "latitude": 51.427788597793466,
      "type": "HV",
      "reference": "KF3172",
      "etaUpdate": true,
      "affectedCustomerCount": 66,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "5cb76faf-5a4b-40ae-8388-a8a1e58a4c13",
      "minLongitude": -1.4777,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.442001462256222,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T02:00:00.000+0000",
      "estimatedRestoration": "2022-11-19T14:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3172'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3172",
      "maxLongitude": -1.4116,
      "minLatitude": 51.4034,
      "name": "RG17 & RG20 Areas",
      "otherUpdate": true,
      "affectedAreas": [
        "RG17 0NY",
        "RG17 0PB",
        "RG17 9RJ",
        "RG17 9RL",
        "RG17 9RN",
        "RG17 9RP",
        "RG17 9RR",
        "RG17 9RW",
        "RG20 8EX",
        "RG20 8EY",
        "RG20 8HB",
        "RG20 8NH",
        "RG20 8NJ",
        "RG20 8NL",
        "RG20 8NN",
        "RG20 8NP"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.4777,
              51.4413
            ],
            [
              -1.4116,
              51.4413
            ],
            [
              -1.4116,
              51.4034
            ],
            [
              -1.4777,
              51.4034
            ],
            [
              -1.4777,
              51.4413
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-19T09:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4413,
      "etrUpdate": true
    },
    {
      "latitude": 51.62281172206627,
      "type": "LV",
      "reference": "KF3178",
      "etaUpdate": true,
      "affectedCustomerCount": 36,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "4b52dc34-57fa-4c1b-ae3d-a2ddbaa09347",
      "minLongitude": -0.8403,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8331668377744883,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T03:56:00.000+0000",
      "estimatedRestoration": "2022-11-19T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3178'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3178",
      "maxLongitude": -0.8261,
      "minLatitude": 51.6189,
      "name": "HP14 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "HP14 3DD",
        "HP14 3DE",
        "HP14 3ED",
        "HP14 3JR",
        "HP14 3JS",
        "HP14 3JU",
        "HP14 3JZ",
        "HP14 3LA",
        "HP14 3LB",
        "HP14 3LD",
        "HP14 3LH",
        "HP14 3LY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.8403,
              51.6266
            ],
            [
              -0.8261,
              51.6266
            ],
            [
              -0.8261,
              51.6189
            ],
            [
              -0.8403,
              51.6189
            ],
            [
              -0.8403,
              51.6266
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-19T05:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.6266,
      "etrUpdate": true
    },
    {
      "latitude": 51.52601779380734,
      "type": "LV",
      "reference": "KF3126",
      "etaUpdate": true,
      "affectedCustomerCount": 27,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "ba7b0b47-edf2-49cf-8326-37915f7c7edf",
      "minLongitude": -0.31,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.3085870825584674,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T04:39:00.000+0000",
      "estimatedRestoration": "2022-11-19T15:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3126'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3126",
      "maxLongitude": -0.3061,
      "minLatitude": 51.5234,
      "name": "W5 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "W5 1NU",
        "W5 1PA",
        "W5 1SH",
        "W5 1SL",
        "W5 1SQ",
        "W5 1SR"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.31,
              51.5285
            ],
            [
              -0.3061,
              51.5285
            ],
            [
              -0.3061,
              51.5234
            ],
            [
              -0.31,
              51.5234
            ],
            [
              -0.31,
              51.5285
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5285,
      "etrUpdate": true
    },
    {
      "latitude": 50.78022064804924,
      "type": "LV",
      "reference": "KF3210",
      "etaUpdate": true,
      "affectedCustomerCount": 22,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "5c76d683-7122-4ffd-87d2-7597ff97feaf",
      "minLongitude": -1.1434,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.1332223020896133,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T06:16:00.000+0000",
      "estimatedRestoration": "2022-11-19T09:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3210'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3210",
      "maxLongitude": -1.1278,
      "minLatitude": 50.7731,
      "name": "PO12 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO12 2AR",
        "PO12 2AT",
        "PO12 2BT",
        "PO12 2BU",
        "PO12 2UL",
        "PO12 2UN",
        "PO12 2UW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.1434,
              50.7822
            ],
            [
              -1.1278,
              50.7822
            ],
            [
              -1.1278,
              50.7731
            ],
            [
              -1.1434,
              50.7731
            ],
            [
              -1.1434,
              50.7822
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-19T07:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.7822,
      "etrUpdate": true
    },
    {
      "latitude": 51.24333431167483,
      "type": "LV",
      "reference": "KF3208",
      "etaUpdate": true,
      "affectedCustomerCount": 30,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "fc1f50f4-0d28-4d7c-9cd3-0a411e45db06",
      "minLongitude": -1.1271,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.1240186951870723,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T06:09:00.000+0000",
      "estimatedRestoration": "2022-11-19T09:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3208'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3208",
      "maxLongitude": -1.1219,
      "minLatitude": 51.2412,
      "name": "RG22 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG22 4LB",
        "RG22 4NJ",
        "RG22 4NL"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.1271,
              51.2453
            ],
            [
              -1.1219,
              51.2453
            ],
            [
              -1.1219,
              51.2412
            ],
            [
              -1.1271,
              51.2412
            ],
            [
              -1.1271,
              51.2453
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-19T08:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.2453,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T06:09:00.000+0000",
      "latitude": 51.51170956996594,
      "estimatedRestoration": "2022-11-19T09:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3207'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3207",
      "reference": "KF3207",
      "etaUpdate": true,
      "affectedCustomerCount": 12,
      "name": "UB7 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "UB7 7LZ"
      ],
      "location": {
        "coordinates": [
          -0.4785197779429843,
          51.51170956996594
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-11-19T07:30:00.000+0000",
      "UUID": "a9ca18e9-b0ea-4d13-a026-b14ece41b522",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "etrUpdate": true,
      "longitude": -0.4785197779429843,
      "resolved": false
    },
    {
      "latitude": 57.00687418356075,
      "type": "HV",
      "reference": "KF2941",
      "etaUpdate": true,
      "affectedCustomerCount": 9,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "945c45b4-2970-4b30-b49c-44b8a0f3f420",
      "minLongitude": -2.4206,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.3594258695990247,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-18T15:06:00.000+0000",
      "estimatedRestoration": "2022-11-19T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF2941'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF2941",
      "maxLongitude": -2.2961,
      "minLatitude": 56.9716,
      "name": "AB31 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "AB31 6AE",
        "AB31 6DF",
        "AB31 6DL",
        "AB39 3TH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.4206,
              57.0298
            ],
            [
              -2.2961,
              57.0298
            ],
            [
              -2.2961,
              56.9716
            ],
            [
              -2.4206,
              56.9716
            ],
            [
              -2.4206,
              57.0298
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-18T18:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 57.0298,
      "etrUpdate": true
    },
    {
      "latitude": 57.04522863866737,
      "type": "HV",
      "reference": "KF2954",
      "etaUpdate": true,
      "affectedCustomerCount": 183,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "8065efac-c26e-4b55-b425-aa9b981559d1",
      "minLongitude": -3.0939,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.0413409087922316,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-18T16:34:00.000+0000",
      "estimatedRestoration": "2022-11-19T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF2954'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF2954",
      "maxLongitude": -2.9811,
      "minLatitude": 57.0052,
      "name": "AB35 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "AB35 5GL",
        "AB35 5GS",
        "AB35 5NE",
        "AB35 5PL",
        "AB35 5PU",
        "AB35 5PW",
        "AB35 5PZ",
        "AB35 5QJ",
        "AB35 5QL",
        "AB35 5QN",
        "AB35 5QP",
        "AB35 5QR",
        "AB35 5QS",
        "AB35 5QT",
        "AB35 5QU",
        "AB35 5QW",
        "AB35 5QX",
        "AB35 5QY",
        "AB35 5SL",
        "AB35 5SP",
        "AB35 5ST"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.0939,
              57.0499
            ],
            [
              -2.9811,
              57.0499
            ],
            [
              -2.9811,
              57.0052
            ],
            [
              -3.0939,
              57.0052
            ],
            [
              -3.0939,
              57.0499
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-18T18:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 57.0499,
      "etrUpdate": true
    },
    {
      "latitude": 57.33900602450045,
      "type": "HV",
      "reference": "KF3109",
      "etaUpdate": true,
      "affectedCustomerCount": 9,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "64f22b2f-c082-49c6-8050-3e1ae93bbd09",
      "minLongitude": -2.723,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.6638861937924383,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-18T16:41:00.000+0000",
      "estimatedRestoration": "2022-11-19T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3109'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3109",
      "maxLongitude": -2.6355,
      "minLatitude": 57.3242,
      "name": "AB52 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "AB52 6NW",
        "AB52 6XQ",
        "AB52 6YD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.723,
              57.3588
            ],
            [
              -2.6355,
              57.3588
            ],
            [
              -2.6355,
              57.3242
            ],
            [
              -2.723,
              57.3242
            ],
            [
              -2.723,
              57.3588
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-18T20:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 57.3588,
      "etrUpdate": true
    },
    {
      "latitude": 57.11962903269727,
      "type": "HV",
      "reference": "KF3168",
      "etaUpdate": true,
      "affectedCustomerCount": 82,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "319b5a02-24aa-497e-a6a1-a00de40997a0",
      "minLongitude": -2.1719,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.1684920934298213,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T03:01:00.000+0000",
      "estimatedRestoration": "2022-11-19T10:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3168'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3168",
      "maxLongitude": -2.1572,
      "minLatitude": 57.1153,
      "name": "AB15 Area",
      "otherUpdate": true,
      "affectedAreas": [
        ".",
        "AB15 9HT",
        "AB15 9JT",
        "AB15 9NN",
        "AB15 9NQ",
        "AB15 9NR",
        "AB15 9PA",
        "AB15 9PB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.1719,
              57.123
            ],
            [
              -2.1572,
              57.123
            ],
            [
              -2.1572,
              57.1153
            ],
            [
              -2.1719,
              57.1153
            ],
            [
              -2.1719,
              57.123
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-19T04:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 57.123,
      "etrUpdate": true
    },
    {
      "latitude": 57.03424159084476,
      "type": "HV",
      "reference": "KF3174",
      "etaUpdate": true,
      "affectedCustomerCount": 220,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "da7e7909-5102-43a9-a978-7d266916e916",
      "minLongitude": -2.6609,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.506296528338676,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T03:39:00.000+0000",
      "estimatedRestoration": "2022-11-19T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3174'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3174",
      "maxLongitude": -2.4602,
      "minLatitude": 56.9984,
      "name": "AB31 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "AB31 5BP",
        "AB31 5HS",
        "AB31 5HU",
        "AB31 6HX",
        "AB31 6LD",
        "AB31 6LE",
        "AB31 6LH",
        "AB31 6LJ",
        "AB31 6LL",
        "AB31 6NH",
        "AB31 6NJ",
        "AB31 6NL",
        "AB31 6NN",
        "AB31 6NY",
        "AB31 6PQ",
        "AB31 6PR",
        "AB31 6PS",
        "AB31 6PT",
        "AB31 6XF"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6609,
              57.0581
            ],
            [
              -2.4602,
              57.0581
            ],
            [
              -2.4602,
              56.9984
            ],
            [
              -2.6609,
              56.9984
            ],
            [
              -2.6609,
              57.0581
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-19T09:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 57.0581,
      "etrUpdate": true
    },
    {
      "latitude": 56.49913704101552,
      "type": "HV",
      "reference": "KF3186",
      "etaUpdate": true,
      "affectedCustomerCount": 42,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "8392b96b-8354-47c8-94c2-a5b2474d0178",
      "minLongitude": -6.942,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -6.811994978010261,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T05:02:00.000+0000",
      "estimatedRestoration": "2022-11-19T09:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3186'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3186",
      "maxLongitude": -6.7945,
      "minLatitude": 56.4867,
      "name": "PA77 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PA77 6TN",
        "PA77 6UH",
        "PA77 6UL"
      ],
      "location": {
        "coordinates": [
          [
            [
              -6.942,
              56.5278
            ],
            [
              -6.7945,
              56.5278
            ],
            [
              -6.7945,
              56.4867
            ],
            [
              -6.942,
              56.4867
            ],
            [
              -6.942,
              56.5278
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-11-19T05:20:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.5278,
      "etrUpdate": true
    },
    {
      "latitude": 56.90934867003747,
      "type": "HV",
      "reference": "KF3203",
      "etaUpdate": true,
      "affectedCustomerCount": 94,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "f8b05d1a-7072-40d5-80a2-e3bd918f8ff9",
      "minLongitude": -2.3232,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.2671366467251906,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T05:46:00.000+0000",
      "estimatedRestoration": "2022-11-19T10:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3203'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3203",
      "maxLongitude": -2.1911,
      "minLatitude": 56.8816,
      "name": "AB39 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "AB30 1LP",
        "AB30 1LQ",
        "AB39 2TL",
        "AB39 2TR",
        "AB39 2TS",
        "AB39 2TU",
        "AB39 2UB",
        "AB39 2UD",
        "AB39 2UE",
        "AB39 2UH",
        "AB39 2UJ",
        "AB39 2XU"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.3232,
              56.9543
            ],
            [
              -2.1911,
              56.9543
            ],
            [
              -2.1911,
              56.8816
            ],
            [
              -2.3232,
              56.8816
            ],
            [
              -2.3232,
              56.9543
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.9543,
      "etrUpdate": true
    },
    {
      "latitude": 57.143308931659305,
      "type": "LV",
      "reference": "KF3209",
      "etaUpdate": true,
      "affectedCustomerCount": 17,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "0c73c5ed-6859-435e-be13-ab166f8f277b",
      "minLongitude": -2.1125,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.1116726566278006,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-11-19T06:11:00.000+0000",
      "estimatedRestoration": "2022-11-19T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KF3209'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KF3209",
      "maxLongitude": -2.1107,
      "minLatitude": 57.1428,
      "name": "AB10 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "AB10 1DW",
        "AB10 1TS",
        "AB10 1TT",
        "AB10 1TX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.1125,
              57.1441
            ],
            [
              -2.1107,
              57.1441
            ],
            [
              -2.1107,
              57.1428
            ],
            [
              -2.1125,
              57.1428
            ],
            [
              -2.1125,
              57.1441
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 57.1441,
      "etrUpdate": true
    }
  ]
}
