{
  "Faults": [
    {
      "latitude": 50.68943202161117,
      "type": "PSI",
      "reference": "216331",
      "etaUpdate": true,
      "affectedCustomerCount": 4,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "dc9b868f-7eea-4c1a-bed0-a3f5ea52294e",
      "minLongitude": -2.6744,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.671208575946793,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T07:00:00.000+0000",
      "estimatedRestoration": "2023-05-05T14:30:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '216331'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/216331",
      "maxLongitude": -2.6681,
      "minLatitude": 50.6867,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT2 9DJ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6744,
              50.6901
            ],
            [
              -2.6681,
              50.6901
            ],
            [
              -2.6681,
              50.6867
            ],
            [
              -2.6744,
              50.6867
            ],
            [
              -2.6744,
              50.6901
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.6901,
      "etrUpdate": true
    },
    {
      "latitude": 50.74082585903731,
      "type": "LV",
      "reference": "KV6843",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-05-04T10:00:00.000+0000",
      "affectedCustomerCount": 17,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "9a205e96-75ca-4e72-8996-481307de1628",
      "minLongitude": -1.69,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.686449815461876,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T08:45:00.000+0000",
      "estimatedRestoration": "2023-05-04T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV6843'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV6843",
      "maxLongitude": -1.6755,
      "minLatitude": 50.7363,
      "name": "BH25 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BH25",
        "BH25 7QE",
        "BH25 7RA",
        "BH25 7RE",
        "BH25 7RF",
        "BH25 7RG",
        "BH25 7RN",
        "BH25 7RQ",
        "BH25 7RW",
        "BH25 7RX",
        "BH25 7SR"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.69,
              50.7453
            ],
            [
              -1.6755,
              50.7453
            ],
            [
              -1.6755,
              50.7363
            ],
            [
              -1.69,
              50.7363
            ],
            [
              -1.69,
              50.7453
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-05-04T10:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.7453,
      "etrUpdate": true
    },
    {
      "latitude": 50.88405741032344,
      "type": "LV",
      "reference": "KV6936",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-05-04T11:00:00.000+0000",
      "affectedCustomerCount": 11,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "08c7bc74-ac1b-46ce-8f13-f9c2fb3343f0",
      "minLongitude": -1.0234,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0214666688171907,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T09:51:00.000+0000",
      "estimatedRestoration": "2023-05-04T19:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV6936'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV6936",
      "maxLongitude": -1.02,
      "minLatitude": 50.8826,
      "name": "PO7 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO7 7QA",
        "PO7 7QB",
        "PO7 7QD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0234,
              50.8855
            ],
            [
              -1.02,
              50.8855
            ],
            [
              -1.02,
              50.8826
            ],
            [
              -1.0234,
              50.8826
            ],
            [
              -1.0234,
              50.8855
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-05-04T10:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8855,
      "etrUpdate": true
    },
    {
      "latitude": 50.58894749109746,
      "type": "LV",
      "reference": "KV7001",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-05-04T11:50:00.000+0000",
      "affectedCustomerCount": 14,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "eb6e1b29-c762-405f-bf70-0b9c3e6b852f",
      "minLongitude": -2.4868,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.4752145278962607,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T10:48:00.000+0000",
      "estimatedRestoration": "2023-05-04T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7001'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7001",
      "maxLongitude": -2.4731,
      "minLatitude": 50.5843,
      "name": "DT4 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT4 9AU",
        "DT4 9AX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.4868,
              50.5904
            ],
            [
              -2.4731,
              50.5904
            ],
            [
              -2.4731,
              50.5843
            ],
            [
              -2.4868,
              50.5843
            ],
            [
              -2.4868,
              50.5904
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-05-04T12:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.5904,
      "etrUpdate": true
    },
    {
      "latitude": 50.932043549450775,
      "type": "LV",
      "reference": "KV6981",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-05-04T12:20:00.000+0000",
      "affectedCustomerCount": 24,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "a237631c-a8aa-4096-b7f0-ab232ab9388f",
      "minLongitude": -2.6634,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.660394567406395,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T10:40:00.000+0000",
      "estimatedRestoration": "2023-05-04T22:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV6981'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV6981",
      "maxLongitude": -2.658,
      "minLatitude": 50.9308,
      "name": "BA20 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BA20 2PL",
        "BA20 2SA",
        "BA20 2SE",
        "BA20 2SF",
        "BA20 2SR"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6634,
              50.9331
            ],
            [
              -2.658,
              50.9331
            ],
            [
              -2.658,
              50.9308
            ],
            [
              -2.6634,
              50.9308
            ],
            [
              -2.6634,
              50.9331
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-05-04T12:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.9331,
      "etrUpdate": true
    },
    {
      "latitude": 51.74534637512392,
      "type": "LV",
      "reference": "KV7176",
      "etaUpdate": true,
      "affectedCustomerCount": 22,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "1cbbd83e-1a9f-4610-88e5-166aa37670a9",
      "minLongitude": -1.2019,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.199094207871259,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T12:48:00.000+0000",
      "estimatedRestoration": "2023-05-04T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7176'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7176",
      "maxLongitude": -1.197,
      "minLatitude": 51.7441,
      "name": "OX3 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "OX3 7JR",
        "OX3 8QX",
        "OX3 8QY",
        "OX3 8RS",
        "OX3 8RT",
        "OX3 8TR"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.2019,
              51.7471
            ],
            [
              -1.197,
              51.7471
            ],
            [
              -1.197,
              51.7441
            ],
            [
              -1.2019,
              51.7441
            ],
            [
              -1.2019,
              51.7471
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-05-04T16:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.7471,
      "etrUpdate": true
    },
    {
      "latitude": 51.481840655455194,
      "type": "HV",
      "reference": "KV7333",
      "etaUpdate": true,
      "affectedCustomerCount": 9,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "cbb2802c-69a2-4b52-b84c-7a6dc45e5ba8",
      "minLongitude": -1.9706,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.9493052732629945,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T14:36:00.000+0000",
      "estimatedRestoration": "2023-05-04T19:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7333'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7333",
      "maxLongitude": -1.9349,
      "minLatitude": 51.4714,
      "name": "SN11 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN11 8SS",
        "SN11 8TA",
        "SN11 8TB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.9706,
              51.4879
            ],
            [
              -1.9349,
              51.4879
            ],
            [
              -1.9349,
              51.4714
            ],
            [
              -1.9706,
              51.4714
            ],
            [
              -1.9706,
              51.4879
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-05-04T15:20:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4879,
      "etrUpdate": true
    },
    {
      "latitude": 51.42040697708541,
      "type": "LV",
      "reference": "KV7392",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-05-04T17:25:00.000+0000",
      "affectedCustomerCount": 16,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "975d9d54-993d-4e25-9854-d8c66bb5cae2",
      "minLongitude": -1.7338,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7298448798053576,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T16:10:00.000+0000",
      "estimatedRestoration": "2023-05-04T20:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7392'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7392",
      "maxLongitude": -1.7268,
      "minLatitude": 51.4188,
      "name": "SN8 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN8 1AA",
        "SN8 1AH",
        "SN8 1BE",
        "SN8 1LT",
        "SN8 1LW",
        "SN8 1NE",
        "SN8 1NG",
        "SN8 1NU"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.7338,
              51.4219
            ],
            [
              -1.7268,
              51.4219
            ],
            [
              -1.7268,
              51.4188
            ],
            [
              -1.7338,
              51.4188
            ],
            [
              -1.7338,
              51.4219
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-05-04T17:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4219,
      "etrUpdate": true
    },
    {
      "latitude": 51.55887942204947,
      "type": "LV",
      "reference": "KV7431",
      "etaUpdate": true,
      "affectedCustomerCount": 1,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "d1754ae4-5472-411f-a5be-ff00b7dae9d4",
      "minLongitude": -0.7304,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.730016694705874,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T13:05:00.000+0000",
      "estimatedRestoration": "2023-05-04T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7431'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7431",
      "maxLongitude": -0.7298,
      "minLatitude": 51.5587,
      "name": "SL6 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SL6 9ET"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.7304,
              51.5591
            ],
            [
              -0.7298,
              51.5591
            ],
            [
              -0.7298,
              51.5587
            ],
            [
              -0.7304,
              51.5587
            ],
            [
              -0.7304,
              51.5591
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5591,
      "etrUpdate": true
    },
    {
      "latitude": 51.54249661330498,
      "type": "LV",
      "reference": "KV7418",
      "etaUpdate": true,
      "affectedCustomerCount": 9,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "0ad881d0-6d7b-435c-acf3-24ce271d0863",
      "minLongitude": -1.78,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7784238965753585,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T16:48:00.000+0000",
      "estimatedRestoration": "2023-05-04T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7418'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7418",
      "maxLongitude": -1.7725,
      "minLatitude": 51.538,
      "name": "SN1 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN1 4EB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.78,
              51.5446
            ],
            [
              -1.7725,
              51.5446
            ],
            [
              -1.7725,
              51.538
            ],
            [
              -1.78,
              51.538
            ],
            [
              -1.78,
              51.5446
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-05-04T18:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "evChargersAffected": [
        "869b27e4-3bb8-4be0-9ed2-7f1047531a96",
        "c1072b44-3bfe-4066-a10a-3b1d9812be61",
        "43c1dca0-94f8-422a-b159-9f5309908a0f",
        "c90bb938-d610-4797-9e56-b0b6d96c0775",
        "e65638d8-639a-42dd-aa83-eb0c3092ff74",
        "6a0c8151-6a42-44ea-a70f-6db2b1a77150",
        "b3d6c79e-1318-40d9-bc62-4874f3215f43",
        "19950f1b-f254-40c0-a8ce-78274d109bfa",
        "a387d97e-c7ce-4530-b577-0eba2aa69df2",
        "e13bf779-9f93-43e1-bb6e-e1f18777d23a",
        "c0e6de67-eaa0-4161-ab1d-cd4b799c449b",
        "166eaece-4e19-4b93-8545-ded40c434840"
      ],
      "maxLatitude": 51.5446,
      "etrUpdate": true
    },
    {
      "latitude": 51.498289466441804,
      "type": "LV",
      "reference": "KV7442",
      "etaUpdate": true,
      "affectedCustomerCount": 11,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "78d9535f-7ff7-424b-9de5-b9581bdbc15a",
      "minLongitude": -0.4305,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.42979629145718035,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-07-21T05:40:00.000+0000",
      "estimatedRestoration": "2023-05-04T20:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7442'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7442",
      "maxLongitude": -0.4293,
      "minLatitude": 51.4972,
      "name": "UB3 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "UB3 1LT",
        "UB3 1NA",
        "UB3 1NB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.4305,
              51.4992
            ],
            [
              -0.4293,
              51.4992
            ],
            [
              -0.4293,
              51.4972
            ],
            [
              -0.4305,
              51.4972
            ],
            [
              -0.4305,
              51.4992
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4992,
      "etrUpdate": true
    },
    {
      "latitude": 51.16185737324876,
      "type": "LV",
      "reference": "KV7437",
      "etaUpdate": true,
      "affectedCustomerCount": 12,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "71e5eee6-b621-4fe1-8312-c27d4cef8893",
      "minLongitude": -0.9717,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9696242056210391,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T17:16:00.000+0000",
      "estimatedRestoration": "2023-05-04T20:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7437'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7437",
      "maxLongitude": -0.9676,
      "minLatitude": 51.16,
      "name": "GU34 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GU34 2NH",
        "GU34 2NN",
        "GU34 2NP",
        "GU34 2NR",
        "GU34 2NW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.9717,
              51.1636
            ],
            [
              -0.9676,
              51.1636
            ],
            [
              -0.9676,
              51.16
            ],
            [
              -0.9717,
              51.16
            ],
            [
              -0.9717,
              51.1636
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-05-04T18:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.1636,
      "etrUpdate": true
    },
    {
      "latitude": 51.45911403988969,
      "type": "LV",
      "reference": "KV7450",
      "etaUpdate": true,
      "affectedCustomerCount": 8,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "78d164ae-2a1d-41b2-9fa4-716240af2314",
      "minLongitude": -0.3661,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.36430716403203045,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T10:48:00.000+0000",
      "estimatedRestoration": "2023-05-04T20:40:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7450'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7450",
      "maxLongitude": -0.3631,
      "minLatitude": 51.4577,
      "name": "TW3 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "TW3 2LF",
        "TW3 2LG",
        "TW3 2LQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.3661,
              51.4602
            ],
            [
              -0.3631,
              51.4602
            ],
            [
              -0.3631,
              51.4577
            ],
            [
              -0.3661,
              51.4577
            ],
            [
              -0.3661,
              51.4602
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4602,
      "etrUpdate": true
    },
    {
      "latitude": 50.891957772761224,
      "type": "HV",
      "reference": "KV7451",
      "etaUpdate": true,
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "00ff0a69-6d05-4ec6-be66-a7b702e83187",
      "minLongitude": -0.6246,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6090244430305923,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T17:44:00.000+0000",
      "estimatedRestoration": "2023-05-04T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7451'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7451",
      "maxLongitude": -0.5959,
      "minLatitude": 50.8864,
      "name": "BN18 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BN18 0NT"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.6246,
              50.8997
            ],
            [
              -0.5959,
              50.8997
            ],
            [
              -0.5959,
              50.8864
            ],
            [
              -0.6246,
              50.8864
            ],
            [
              -0.6246,
              50.8997
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8997,
      "etrUpdate": true
    },
    {
      "latitude": 56.00010029918838,
      "type": "HV",
      "reference": "KV7223",
      "etaUpdate": true,
      "affectedCustomerCount": 1,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "4b68dff6-360b-48b5-a9fc-87ae68c3abfc",
      "minLongitude": -5.1644,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.1120379382410235,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T13:20:00.000+0000",
      "estimatedRestoration": "2023-05-04T18:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7223'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7223",
      "maxLongitude": -5.0137,
      "minLatitude": 55.9645,
      "name": "PA23 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PA23 8RG"
      ],
      "location": {
        "coordinates": [
          [
            [
              -5.1644,
              56.0711
            ],
            [
              -5.0137,
              56.0711
            ],
            [
              -5.0137,
              55.9645
            ],
            [
              -5.1644,
              55.9645
            ],
            [
              -5.1644,
              56.0711
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-05-04T14:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.0711,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-05-04T16:11:00.000+0000",
      "latitude": 58.442485011506264,
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV7394'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV7394",
      "reference": "KV7394",
      "maxLongitude": -3.0756,
      "etaUpdate": true,
      "minLatitude": 58.4374,
      "name": "KW1 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "KW1 4JH",
        "KW1 4JJ",
        "KW1 4JR",
        "KW1 4JW",
        "KW1 5HA"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.0876,
              58.4444
            ],
            [
              -3.0756,
              58.4444
            ],
            [
              -3.0756,
              58.4374
            ],
            [
              -3.0876,
              58.4374
            ],
            [
              -3.0876,
              58.4444
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "15c960ca-117b-442c-b20e-c290c8e45f4b",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -3.0876,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 58.4444,
      "etrUpdate": true,
      "longitude": -3.0813673878711203,
      "resolved": false
    }
  ]
}
