{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-13T07:30:00.000+0000",
      "latitude": 50.83600470980545,
      "estimatedRestoration": "2022-01-14T17:30:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '205085'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/205085",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.83599,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.20818
            }
          ],
          "name": "PO14 2HS",
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "205085",
      "name": "PO14 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO14 2HS"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.2081796009140675,
          50.83600470980545
        ],
        "type": "Point"
      },
      "UUID": "600d2015-c78c-438c-b912-9e5d629ef94d",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.2081796009140675,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-13T23:45:00.000+0000",
      "latitude": 51.34055842510735,
      "estimatedRestoration": "2022-01-14T10:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JJ2487'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JJ2487",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.3422,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.82668
            },
            {
              "py/object": "Point",
              "latitude": 51.33875,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.82404
            },
            {
              "py/object": "Point",
              "latitude": 51.33922,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.82121
            },
            {
              "py/object": "Point",
              "latitude": 51.33988,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.81815
            },
            {
              "py/object": "Point",
              "latitude": 51.34013,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.81779
            },
            {
              "py/object": "Point",
              "latitude": 51.34125,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.81832
            },
            {
              "py/object": "Point",
              "latitude": 51.34235,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.8196
            },
            {
              "py/object": "Point",
              "latitude": 51.3422,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.82668
            }
          ],
          "subCodes": [
            "GU46 6UZ",
            "GU46 6XA",
            "GU46 6XD",
            "GU46 6XE",
            "GU46 6XF",
            "GU46 6XH",
            "GU46 7AB",
            "GU46 7TL",
            "GU46 7UA",
            "GU46 7UE",
            "GU46 7UG",
            "GU46 7UH",
            "GU46 7UN",
            "GU46 7UR"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JJ2487",
      "engineerOnSiteTime": "2022-01-13T09:20:00.000+0000",
      "name": "GU46 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU46 6UZ",
        "GU46 6XA",
        "GU46 6XD",
        "GU46 6XE",
        "GU46 6XF",
        "GU46 6XH",
        "GU46 7AB",
        "GU46 7TL",
        "GU46 7UA",
        "GU46 7UE",
        "GU46 7UG",
        "GU46 7UH",
        "GU46 7UN",
        "GU46 7UR"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.82668,
              51.3422
            ],
            [
              -0.82404,
              51.33875
            ],
            [
              -0.82121,
              51.33922
            ],
            [
              -0.81815,
              51.33988
            ],
            [
              -0.81779,
              51.34013
            ],
            [
              -0.81832,
              51.34125
            ],
            [
              -0.8196,
              51.34235
            ],
            [
              -0.82668,
              51.3422
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "cf18ea44-0f32-4195-891b-b487b9c33978",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8208646491169741,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-14T03:56:00.000+0000",
      "latitude": 51.58204780215568,
      "estimatedRestoration": "2022-01-14T15:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JJ2983'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JJ2983",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.58273,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.74736
            },
            {
              "py/object": "Point",
              "latitude": 51.58227,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.74729
            },
            {
              "py/object": "Point",
              "latitude": 51.58167,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.74631
            },
            {
              "py/object": "Point",
              "latitude": 51.58145,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.74529
            },
            {
              "py/object": "Point",
              "latitude": 51.58185,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.74403
            },
            {
              "py/object": "Point",
              "latitude": 51.58201,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.74445
            },
            {
              "py/object": "Point",
              "latitude": 51.58273,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.74736
            }
          ],
          "subCodes": [
            "SN3 4FG",
            "SN3 4GH",
            "SN3 4NB",
            "SN3 4NE",
            "SN3 4NF",
            "SN3 4NH",
            "SN3 4NQ"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JJ2983",
      "engineerOnSiteTime": "2022-01-14T04:25:00.000+0000",
      "name": "SN3 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN3 4FG",
        "SN3 4GH",
        "SN3 4NB",
        "SN3 4NE",
        "SN3 4NF",
        "SN3 4NH",
        "SN3 4NQ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.74736,
              51.58273
            ],
            [
              -1.74729,
              51.58227
            ],
            [
              -1.74631,
              51.58167
            ],
            [
              -1.74529,
              51.58145
            ],
            [
              -1.74403,
              51.58185
            ],
            [
              -1.74445,
              51.58201
            ],
            [
              -1.74736,
              51.58273
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "cba54f57-0b5c-4f80-9cfa-0333f4496c83",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7463801511434198,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-14T07:38:00.000+0000",
      "latitude": 51.24062932538427,
      "estimatedRestoration": "2022-01-14T11:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JJ3023'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JJ3023",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.24025,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.14731
            },
            {
              "py/object": "Point",
              "latitude": 51.24122,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.14563
            },
            {
              "py/object": "Point",
              "latitude": 51.24042,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.14549
            },
            {
              "py/object": "Point",
              "latitude": 51.24025,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.14731
            }
          ],
          "subCodes": [
            "RG22 5JS",
            "RG22 5QX",
            "RG22 5QY"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JJ3023",
      "name": "RG22 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG22 5JS",
        "RG22 5QX",
        "RG22 5QY"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.14731,
              51.24025
            ],
            [
              -1.14563,
              51.24122
            ],
            [
              -1.14549,
              51.24042
            ],
            [
              -1.14731,
              51.24025
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-01-14T09:00:00.000+0000",
      "UUID": "857c4750-b92c-46d5-a4ca-73d49598c7ec",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.1461454146981127,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-14T08:30:00.000+0000",
      "latitude": 50.95438098641811,
      "estimatedRestoration": "2022-01-14T16:30:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '204617'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/204617",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.95017,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.65943
            },
            {
              "py/object": "Point",
              "latitude": 50.95568,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.65514
            },
            {
              "py/object": "Point",
              "latitude": 50.95792,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.64596
            },
            {
              "py/object": "Point",
              "latitude": 50.95017,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.65943
            }
          ],
          "subCodes": [
            "GU28 0QJ",
            "GU28 0QL",
            "GU28 0QQ"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "204617",
      "name": "GU28 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU28 0QJ",
        "GU28 0QL",
        "GU28 0QQ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.65943,
              50.95017
            ],
            [
              -0.65514,
              50.95568
            ],
            [
              -0.64596,
              50.95792
            ],
            [
              -0.65943,
              50.95017
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "5981eef5-82b4-4854-9d14-686fa2374fac",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6538328916518101,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-14T07:47:00.000+0000",
      "latitude": 50.75842874040874,
      "estimatedRestoration": "2022-01-14T11:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JJ3026'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JJ3026",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.75852,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.2798
            }
          ],
          "name": "PO32 6AU",
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JJ3026",
      "name": "PO32 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO32 6AU"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.279582683690743,
          50.75842874040874
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-01-14T08:30:00.000+0000",
      "UUID": "dbbbc6dd-330f-4e4c-a34f-2dba7e116f33",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.279582683690743,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-14T08:31:00.000+0000",
      "latitude": 57.4834248710029,
      "estimatedRestoration": "2022-01-14T11:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JJ3038'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JJ3038",
      "reference": "JJ3038",
      "name": "IV2 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV2 5BP",
        "IV2 5BS",
        "IV2 5EA",
        "IV2 5EB",
        "IV2 5EF",
        "IV2 5EQ",
        "IV2 5JQ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -4.0990903411013235,
          57.4834248710029
        ],
        "type": "Point"
      },
      "UUID": "1886fa1b-8a5c-4b0c-9ee0-aaa34274cfb6",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -4.0990903411013235,
      "resolved": false
    }
  ]
}
