{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-26T08:41:00.000+0000",
      "latitude": 50.7952329387835,
      "estimatedRestoration": "2022-04-27T02:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS2705'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS2705",
      "reference": "JS2705",
      "name": "DT2 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT2 0HA",
        "DT2 0HY",
        "DT2 0HZ",
        "DT2 0JA",
        "DT2 0JB",
        "DT2 0JD",
        "DT2 0JN"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.5822995981688326,
          50.7952329387835
        ],
        "type": "Point"
      },
      "UUID": "ce159a5b-8d9f-4cc7-b282-bae59751aede",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.5822995981688326,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-26T13:17:00.000+0000",
      "latitude": 51.36217935498938,
      "estimatedRestoration": "2022-04-26T22:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS2927'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS2927",
      "reference": "JS2927",
      "name": "SN12 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN12 6EH",
        "SN12 6EL",
        "SN12 8PB"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.154639280520337,
          51.36217935498938
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-04-26T13:45:00.000+0000",
      "UUID": "25dcb095-81a3-4c08-bbb1-d7f2bce7f25c",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.154639280520337,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-26T17:13:00.000+0000",
      "latitude": 51.53993194283876,
      "estimatedRestoration": "2022-04-26T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS3007'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS3007",
      "reference": "JS3007",
      "name": "UB8 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "UB8 2RD",
        "UB8 2RE",
        "UB8 2RF",
        "UB8 2RG"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.4851637098171066,
          51.53993194283876
        ],
        "type": "Point"
      },
      "UUID": "4a8f498d-3bd9-4748-9bf3-e0cf803e4579",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.4851637098171066,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-26T17:40:00.000+0000",
      "latitude": 51.514160318857975,
      "estimatedRestoration": "2022-04-26T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS3030'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS3030",
      "reference": "JS3030",
      "name": "SL2 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SL2 5HF"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.580026118731972,
          51.514160318857975
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-04-26T16:00:00.000+0000",
      "UUID": "92bb19e8-8609-4377-8553-5ca4f2cf0757",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.580026118731972,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-26T17:42:00.000+0000",
      "latitude": 51.26615093138028,
      "estimatedRestoration": "2022-04-26T21:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS3031'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS3031",
      "reference": "JS3031",
      "name": "RG27 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG27 8SX",
        "RG27 8SZ",
        "RG27 8TB"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.8788136778972148,
          51.26615093138028
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-04-26T21:00:00.000+0000",
      "UUID": "a118aa16-bc5f-47c6-a17e-6e73b5a3bf6a",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8788136778972148,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-26T19:18:00.000+0000",
      "latitude": 51.13453676024352,
      "estimatedRestoration": "2022-04-26T22:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS3061'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS3061",
      "reference": "JS3061",
      "name": "GU8 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU8 5TD",
        "GU8 5UA",
        "GU8 5UB",
        "GU8 5UD",
        "GU8 5UE",
        "GU8 5UF",
        "GU8 5UG",
        "GU8 5UQ",
        "GU8 5UR",
        "GU8 5UU",
        "GU8 5UX",
        "GU8 5UY"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.6550761412932766,
          51.13453676024352
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-04-26T20:20:00.000+0000",
      "UUID": "16547016-1774-44d9-bec9-c87729254205",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6550761412932766,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-26T20:23:00.000+0000",
      "latitude": 51.24847808580208,
      "estimatedRestoration": "2022-04-26T23:15:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS3081'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS3081",
      "reference": "JS3081",
      "name": "GU12 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU12 6BU",
        "GU12 6LJ",
        "GU12 6LQ",
        "GU12 6NA",
        "GU12 6NB",
        "GU12 6NE",
        "GU12 6RL",
        "GU12 6RP",
        "GU12 6RQ",
        "GU12 6RT",
        "GU12 6RW",
        "GU12 6RX",
        "GU12 6RZ",
        "GU12 6SD"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.7214766163571107,
          51.24847808580208
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-04-26T20:50:00.000+0000",
      "UUID": "f6458cdb-26ef-41f7-bd48-184cdd7e1d14",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7214766163571107,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-26T20:36:00.000+0000",
      "latitude": 51.562513780539696,
      "estimatedRestoration": "2022-04-26T23:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS3087'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS3087",
      "reference": "JS3087",
      "name": "SN4 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN3 4AJ",
        "SN4 0AA",
        "SN4 0AT",
        "SN4 0SN",
        "SN4 0UY"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.7094140576240797,
          51.562513780539696
        ],
        "type": "Point"
      },
      "UUID": "22ddc611-71f0-4615-a4fa-6b63e9859983",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7094140576240797,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-25T06:00:00.000+0000",
      "latitude": 56.59484562207691,
      "estimatedRestoration": "2022-04-29T16:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '206904'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/206904",
      "reference": "206904",
      "name": "DD11 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "DD11 2QR",
        "DD11 4RW",
        "DD11 5RG"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.6261701718912582,
          56.59484562207691
        ],
        "type": "Point"
      },
      "UUID": "e856f5ac-52d2-4e6b-b6af-5d5dd1483949",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.6261701718912582,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-26T16:19:00.000+0000",
      "latitude": 56.50516918742905,
      "estimatedRestoration": "2022-04-26T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS3001'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS3001",
      "reference": "JS3001",
      "name": "DD7 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "DD7 6HJ",
        "DD7 6HP"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.7139486080726356,
          56.50516918742905
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-04-26T17:30:00.000+0000",
      "UUID": "bbffc2f7-4f45-4624-87de-1564c48233e9",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.7139486080726356,
      "resolved": false
    }
  ]
}
