{
  "Faults": [
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-03T17:33:00.000+0000",
      "latitude": 51.60886256364756,
      "estimatedRestoration": "2023-04-05T19:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT1688'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT1688",
      "reference": "KT1688",
      "etaUpdate": true,
      "affectedCustomerCount": 1,
      "name": "UB9 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "UB9 6JY"
      ],
      "location": {
        "coordinates": [
          -0.47871135171246504,
          51.60886256364756
        ],
        "type": "Point"
      },
      "UUID": "ca3d3d06-6671-40dc-b17c-23852d0a3952",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "etrUpdate": true,
      "longitude": -0.47871135171246504,
      "resolved": false
    },
    {
      "latitude": 51.50646418387752,
      "type": "HV",
      "reference": "KT2009",
      "etaUpdate": true,
      "affectedCustomerCount": 16,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "99587b7a-6169-458b-a15d-6e0d794e5f62",
      "minLongitude": -2.3332,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.2928417982762697,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-04T08:56:00.000+0000",
      "estimatedRestoration": "2023-04-04T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT2009'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT2009",
      "maxLongitude": -2.2709,
      "minLatitude": 51.4938,
      "name": "SN14 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GL9 1HR",
        "SN14 7JL",
        "SN14 7PA",
        "SN14 7PB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.3332,
              51.5224
            ],
            [
              -2.2709,
              51.5224
            ],
            [
              -2.2709,
              51.4938
            ],
            [
              -2.3332,
              51.4938
            ],
            [
              -2.3332,
              51.5224
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5224,
      "etrUpdate": true
    },
    {
      "latitude": 51.20832877974389,
      "type": "LV",
      "reference": "KT1967",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-04T09:00:00.000+0000",
      "affectedCustomerCount": 1,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "e57b34ba-f439-4660-aee7-b21a007fb826",
      "minLongitude": -1.4803,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.4799574790352379,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-04T08:22:00.000+0000",
      "estimatedRestoration": "2023-04-05T01:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT1967'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT1967",
      "maxLongitude": -1.4796,
      "minLatitude": 51.208,
      "name": "SP10 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SP10 1LT"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.4803,
              51.2087
            ],
            [
              -1.4796,
              51.2087
            ],
            [
              -1.4796,
              51.208
            ],
            [
              -1.4803,
              51.208
            ],
            [
              -1.4803,
              51.2087
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-04T09:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.2087,
      "etrUpdate": true
    },
    {
      "latitude": 51.558208233176835,
      "type": "LV",
      "reference": "KT2460",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-04T17:00:00.000+0000",
      "affectedCustomerCount": 13,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "79ddf4f4-4b86-4c28-b14e-b64d185f38fe",
      "minLongitude": -0.8737,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8673493902188023,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-04T14:40:00.000+0000",
      "estimatedRestoration": "2023-04-05T02:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT2460'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT2460",
      "maxLongitude": -0.8469,
      "minLatitude": 51.5454,
      "name": "RG9 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG9 3AF",
        "RG9 3AY",
        "RG9 3BB",
        "RG9 3BD",
        "RG9 3BE",
        "RG9 3BH",
        "RG9 3BJ",
        "RG9 3BN"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.8737,
              51.562
            ],
            [
              -0.8469,
              51.562
            ],
            [
              -0.8469,
              51.5454
            ],
            [
              -0.8737,
              51.5454
            ],
            [
              -0.8737,
              51.562
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-04T16:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.562,
      "etrUpdate": true
    },
    {
      "latitude": 50.74548202781766,
      "type": "LV",
      "reference": "KT2550",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-04T18:15:00.000+0000",
      "affectedCustomerCount": 13,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "ce25c41e-0941-4e54-8fc0-6ad0eebfff8e",
      "minLongitude": -1.8098,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7896719639817822,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-04T17:54:00.000+0000",
      "estimatedRestoration": "2023-04-05T00:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT2550'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT2550",
      "maxLongitude": -1.7532,
      "minLatitude": 50.725,
      "name": "BH23 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BH23 2GZ",
        "BH23 2LX",
        "BH23 2LZ",
        "BH23 2NA",
        "BH23 2NB",
        "BH23 2NP",
        "BH23 2PT",
        "BH6 5JG"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.8098,
              50.7495
            ],
            [
              -1.7532,
              50.7495
            ],
            [
              -1.7532,
              50.725
            ],
            [
              -1.8098,
              50.725
            ],
            [
              -1.8098,
              50.7495
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.7495,
      "etrUpdate": true
    },
    {
      "latitude": 51.708229412028665,
      "type": "HV",
      "reference": "KT2597",
      "etaUpdate": true,
      "affectedCustomerCount": 23,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "c4c46982-a62a-45f0-8d10-62ff442330f6",
      "minLongitude": -1.7236,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7033879996484433,
      "resolved": false,
      "py/object": "Fault",
      "Messages": [
        {
          "py/object": "Message",
          "senderName": "james.secker@sse.com",
          "senderUserId": "502b84f7-adfc-4d7c-b7ee-84662532950c",
          "text": "Engineers are responding to a main network fault in the area. We aim to restore power by 23:30.",
          "UUID": "84e3c5b6-36d6-4815-b232-ce7c7ae7b8cf",
          "py/class": "http://opengrid.com/givr/1.0#//Message",
          "sentDateTime": "2023-04-04T19:46:29.598+0000"
        }
      ],
      "srtUpdate": true,
      "loggedAt": "2023-04-04T19:26:00.000+0000",
      "estimatedRestoration": "2023-04-05T05:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT2597'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT2597",
      "maxLongitude": -1.6879,
      "minLatitude": 51.6916,
      "name": "GL7 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GL7 3BE",
        "GL7 3DY",
        "GL7 3EA",
        "GL7 3EB",
        "GL7 3GH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.7236,
              51.7258
            ],
            [
              -1.6879,
              51.7258
            ],
            [
              -1.6879,
              51.6916
            ],
            [
              -1.7236,
              51.6916
            ],
            [
              -1.7236,
              51.7258
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.7258,
      "etrUpdate": true
    },
    {
      "latitude": 50.94525081307599,
      "type": "LV",
      "reference": "KT2601",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-04T20:30:00.000+0000",
      "affectedCustomerCount": 48,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "e95b66f7-dd45-4064-8788-cc6727b55042",
      "minLongitude": -2.5264,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.5224247668560205,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-04T19:34:00.000+0000",
      "estimatedRestoration": "2023-04-05T04:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT2601'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT2601",
      "maxLongitude": -2.5186,
      "minLatitude": 50.9432,
      "name": "DT9 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT9 3AU",
        "DT9 3FA",
        "DT9 3HH",
        "DT9 3HJ",
        "DT9 3HL",
        "DT9 3HP",
        "DT9 3HQ",
        "DT9 3HS",
        "DT9 3HW",
        "DT9 6BH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.5264,
              50.9484
            ],
            [
              -2.5186,
              50.9484
            ],
            [
              -2.5186,
              50.9432
            ],
            [
              -2.5264,
              50.9432
            ],
            [
              -2.5264,
              50.9484
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-04T20:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.9484,
      "etrUpdate": true
    },
    {
      "latitude": 51.223455851466966,
      "type": "LV",
      "reference": "KT2637",
      "etaUpdate": true,
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "72ed9425-722c-43ce-a93f-fe15570eebe7",
      "minLongitude": -2.3209,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.318334120417559,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-04T20:44:00.000+0000",
      "estimatedRestoration": "2023-04-05T04:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT2637'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT2637",
      "maxLongitude": -2.3172,
      "minLatitude": 51.2224,
      "name": "BA11 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BA11 1PA",
        "BA11 1PB",
        "BA11 1PJ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.3209,
              51.2249
            ],
            [
              -2.3172,
              51.2249
            ],
            [
              -2.3172,
              51.2224
            ],
            [
              -2.3209,
              51.2224
            ],
            [
              -2.3209,
              51.2249
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-05T01:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.2249,
      "etrUpdate": true
    },
    {
      "latitude": 50.90166577723181,
      "type": "LV",
      "reference": "KT2641",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-04T21:30:00.000+0000",
      "affectedCustomerCount": 19,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "b0234a3e-ef43-4c3c-a056-22317d7963a7",
      "minLongitude": -1.0207,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0183388017649146,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-04T21:01:00.000+0000",
      "estimatedRestoration": "2023-04-05T09:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT2641'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT2641",
      "maxLongitude": -1.0166,
      "minLatitude": 50.9004,
      "name": "PO8 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO8 8JH",
        "PO8 8JL",
        "PO8 8JN",
        "PO8 8NB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0207,
              50.9034
            ],
            [
              -1.0166,
              50.9034
            ],
            [
              -1.0166,
              50.9004
            ],
            [
              -1.0207,
              50.9004
            ],
            [
              -1.0207,
              50.9034
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-04T21:40:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.9034,
      "etrUpdate": true
    },
    {
      "latitude": 51.52326033243132,
      "type": "LV",
      "reference": "KT2689",
      "etaUpdate": true,
      "affectedCustomerCount": 19,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "6dff6578-17e8-465b-b804-fc046a952a52",
      "minLongitude": -0.7493,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7215374931699674,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-04T23:13:00.000+0000",
      "estimatedRestoration": "2023-04-05T03:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT2689'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT2689",
      "maxLongitude": -0.6254,
      "minLatitude": 51.484,
      "name": "SL6 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SL4 5JF",
        "SL6 6SA",
        "SL6 6SB",
        "SL6 6SL",
        "SL6 6SQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.7493,
              51.5363
            ],
            [
              -0.6254,
              51.5363
            ],
            [
              -0.6254,
              51.484
            ],
            [
              -0.7493,
              51.484
            ],
            [
              -0.7493,
              51.5363
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-05T00:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5363,
      "etrUpdate": true
    },
    {
      "latitude": 56.41819978148876,
      "type": "HV",
      "reference": "KT2633",
      "etaUpdate": true,
      "affectedCustomerCount": 28,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "d1b58638-d8ce-4dc6-a169-6ef4d70c7b0e",
      "minLongitude": -3.5038,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.4832059382529055,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-04T20:31:00.000+0000",
      "estimatedRestoration": "2023-04-05T03:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT2633'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT2633",
      "maxLongitude": -3.4589,
      "minLatitude": 56.41,
      "name": "PH1 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PH1 3EE",
        "PH1 3EQ",
        "PH1 3JP"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.5038,
              56.4297
            ],
            [
              -3.4589,
              56.4297
            ],
            [
              -3.4589,
              56.41
            ],
            [
              -3.5038,
              56.41
            ],
            [
              -3.5038,
              56.4297
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-04T21:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.4297,
      "etrUpdate": true
    }
  ]
}
