{
  "Faults": [
    {
      "latitude": 51.10356531890351,
      "type": "LV",
      "reference": "MN4508",
      "etaUpdate": true,
      "affectedCustomerCount": 19,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "4ddfd205-8c3d-488f-a257-99c10513a294",
      "minLongitude": -1.3111,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.305655260766611,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-09-22T12:20:00.000+0000",
      "estimatedRestoration": "2023-09-22T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MN4508'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MN4508",
      "maxLongitude": -1.3032,
      "minLatitude": 51.1004,
      "name": "SO23 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SO23 7JU",
        "SO23 7LZ",
        "SO23 7NA",
        "SO23 7NB",
        "SO23 7ND",
        "SO23 7NG",
        "SO23 7NW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.3111,
              51.1095
            ],
            [
              -1.3032,
              51.1095
            ],
            [
              -1.3032,
              51.1004
            ],
            [
              -1.3111,
              51.1004
            ],
            [
              -1.3111,
              51.1095
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.1095,
      "etrUpdate": true
    },
    {
      "latitude": 51.39548576829993,
      "type": "LV",
      "reference": "MN4522",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-09-22T13:40:00.000+0000",
      "affectedCustomerCount": 27,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "9b560bcb-3f4d-4ddc-8a2a-2c454570bb97",
      "minLongitude": -2.1474,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.139257304973841,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-09-22T12:28:00.000+0000",
      "estimatedRestoration": "2023-09-22T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MN4522'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MN4522",
      "maxLongitude": -2.1251,
      "minLatitude": 51.3851,
      "name": "SN12 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN12 7PT",
        "SN12 7PU",
        "SN12 7PX",
        "SN12 7PY",
        "SN12 7PZ",
        "SN12 7QE",
        "SN12 7QJ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.1474,
              51.402
            ],
            [
              -2.1251,
              51.402
            ],
            [
              -2.1251,
              51.3851
            ],
            [
              -2.1474,
              51.3851
            ],
            [
              -2.1474,
              51.402
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-09-22T14:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.402,
      "etrUpdate": true
    },
    {
      "latitude": 51.119499634459956,
      "type": "LV",
      "reference": "MN4612",
      "etaUpdate": true,
      "affectedCustomerCount": 22,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "e5d5e8a5-77bf-4bf2-af56-8f3da61c2fda",
      "minLongitude": -1.3463,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.3382496889900286,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-09-22T13:11:00.000+0000",
      "estimatedRestoration": "2023-09-22T18:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MN4612'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MN4612",
      "maxLongitude": -1.3307,
      "minLatitude": 51.1152,
      "name": "SO21 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SO21 2RA",
        "SO21 3BU",
        "SO21 3ER",
        "SO21 3EU",
        "SO21 3EW",
        "SO21 3HA",
        "SO21 3HB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.3463,
              51.1242
            ],
            [
              -1.3307,
              51.1242
            ],
            [
              -1.3307,
              51.1152
            ],
            [
              -1.3463,
              51.1152
            ],
            [
              -1.3463,
              51.1242
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-09-22T15:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.1242,
      "etrUpdate": true
    },
    {
      "latitude": 51.563483626823896,
      "type": "LV",
      "reference": "MN4822",
      "etaUpdate": true,
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "212dccab-4c3b-4b37-9a21-eb15264fdd21",
      "minLongitude": -0.4951,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.4859682461127475,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-09-22T16:13:00.000+0000",
      "estimatedRestoration": "2023-09-22T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MN4822'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MN4822",
      "maxLongitude": -0.4767,
      "minLatitude": 51.5585,
      "name": "UB9 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "UB9 4NA"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.4951,
              51.5666
            ],
            [
              -0.4767,
              51.5666
            ],
            [
              -0.4767,
              51.5585
            ],
            [
              -0.4951,
              51.5585
            ],
            [
              -0.4951,
              51.5666
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-09-22T19:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5666,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-09-22T16:12:00.000+0000",
      "latitude": 50.9596262093531,
      "estimatedRestoration": "2023-09-22T21:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MN4813'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MN4813",
      "reference": "MN4813",
      "etaUpdate": true,
      "affectedCustomerCount": 8,
      "name": "SP5 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SP5 5PP",
        "SP5 5PR",
        "SP5 5PS"
      ],
      "location": {
        "coordinates": [
          -2.083713783185943,
          50.9596262093531
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2023-09-22T19:00:00.000+0000",
      "UUID": "9ed2f79f-f39f-40f8-aa09-822afd978dee",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "etrUpdate": true,
      "longitude": -2.083713783185943,
      "resolved": false
    },
    {
      "latitude": 51.41645407530545,
      "type": "LV",
      "reference": "MN4873",
      "etaUpdate": true,
      "affectedCustomerCount": 14,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "d72dd664-bec9-4d50-bc92-491288de65f7",
      "minLongitude": -0.7378,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7348730065295913,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-09-22T17:17:00.000+0000",
      "estimatedRestoration": "2023-09-22T21:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MN4873'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MN4873",
      "maxLongitude": -0.7332,
      "minLatitude": 51.4149,
      "name": "RG12 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG12 2GP",
        "RG12 2NH",
        "RG12 2NN",
        "RG12 2NP",
        "RG12 2NR",
        "RG12 2TR",
        "RG12 2TX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.7378,
              51.4182
            ],
            [
              -0.7332,
              51.4182
            ],
            [
              -0.7332,
              51.4149
            ],
            [
              -0.7378,
              51.4149
            ],
            [
              -0.7378,
              51.4182
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-09-22T18:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "evChargersAffected": [
        "714432be-bbe8-496e-9c08-9a91b5d864bd"
      ],
      "maxLatitude": 51.4182,
      "etrUpdate": true
    },
    {
      "latitude": 50.930757722474254,
      "type": "LV",
      "reference": "MN4880",
      "etaUpdate": true,
      "affectedCustomerCount": 23,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "70966ff3-3a17-4b0b-a0b7-f735fee85e1f",
      "minLongitude": -1.299,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.2963627317845623,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-09-22T17:29:00.000+0000",
      "estimatedRestoration": "2023-09-22T23:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MN4880'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MN4880",
      "maxLongitude": -1.2896,
      "minLatitude": 50.9284,
      "name": "SO30 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SO30 2AG",
        "SO30 2RF",
        "SO30 2RX",
        "SO30 2RZ",
        "SO30 2XB",
        "SO30 2XD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.299,
              50.9332
            ],
            [
              -1.2896,
              50.9332
            ],
            [
              -1.2896,
              50.9284
            ],
            [
              -1.299,
              50.9284
            ],
            [
              -1.299,
              50.9332
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-09-22T18:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.9332,
      "etrUpdate": true
    },
    {
      "latitude": 57.15105210271097,
      "type": "LV",
      "reference": "MN4897",
      "etaUpdate": true,
      "affectedCustomerCount": 5,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "940a727d-c77f-44bc-85a5-a22e8fff766e",
      "minLongitude": -6.1135,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -6.09985961246866,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-09-22T17:51:00.000+0000",
      "estimatedRestoration": "2023-09-22T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MN4897'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MN4897",
      "maxLongitude": -6.0747,
      "minLatitude": 57.1335,
      "name": "IV49 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "IV49 9BJ",
        "IV49 9BL"
      ],
      "location": {
        "coordinates": [
          [
            [
              -6.1135,
              57.175
            ],
            [
              -6.0747,
              57.175
            ],
            [
              -6.0747,
              57.1335
            ],
            [
              -6.1135,
              57.1335
            ],
            [
              -6.1135,
              57.175
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-09-22T18:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 57.175,
      "etrUpdate": true
    },
    {
      "latitude": 55.63429800921919,
      "type": "HV",
      "reference": "MN4903",
      "etaUpdate": true,
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "75da5cdf-a792-43dc-b097-0f6d8fe2e6a6",
      "minLongitude": -5.6805,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.6617551750240365,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-09-22T16:33:00.000+0000",
      "estimatedRestoration": "2023-09-22T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MN4903'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MN4903",
      "maxLongitude": -5.5623,
      "minLatitude": 55.6163,
      "name": "PA29 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PA29 6XF"
      ],
      "location": {
        "coordinates": [
          [
            [
              -5.6805,
              55.6601
            ],
            [
              -5.5623,
              55.6601
            ],
            [
              -5.5623,
              55.6163
            ],
            [
              -5.6805,
              55.6163
            ],
            [
              -5.6805,
              55.6601
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-09-22T17:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 55.6601,
      "etrUpdate": true
    }
  ]
}
