{
  "Faults": [
    {
      "latitude": 51.595862580822555,
      "type": "LV",
      "reference": "KM5548",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-27T12:30:00.000+0000",
      "affectedCustomerCount": 24,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "6b7c2499-b295-44f9-bf3f-e295dc2d6c8a",
      "minLongitude": -1.7822,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7795794093830521,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-27T11:15:00.000+0000",
      "estimatedRestoration": "2023-01-27T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KM5548'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KM5548",
      "maxLongitude": -1.7717,
      "minLatitude": 51.5898,
      "name": "SN2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN2 5HA",
        "SN2 5HN",
        "SN2 5HR",
        "SN2 5HS",
        "SN2 5JE",
        "SN2 5LZ",
        "SN2 7AS",
        "SN25 4AD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.7822,
              51.5986
            ],
            [
              -1.7717,
              51.5986
            ],
            [
              -1.7717,
              51.5898
            ],
            [
              -1.7822,
              51.5898
            ],
            [
              -1.7822,
              51.5986
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-27T12:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "evChargersAffected": [
        "c9605308-b0f4-4374-ac0a-381298cd38d7"
      ],
      "maxLatitude": 51.5986,
      "etrUpdate": true
    },
    {
      "latitude": 51.7192549424264,
      "type": "LV",
      "reference": "KM5830",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-27T18:45:00.000+0000",
      "affectedCustomerCount": 33,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "bd4234c3-801e-4fea-80b9-5382ad3b0970",
      "minLongitude": -1.1982,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.195342575069258,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-27T17:41:00.000+0000",
      "estimatedRestoration": "2023-01-28T02:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KM5830'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KM5830",
      "maxLongitude": -1.1936,
      "minLatitude": 51.7185,
      "name": "OX4 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "OX4 6PA",
        "OX4 6RA",
        "OX4 6RB",
        "OX4 6RD",
        "OX4 6RE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.1982,
              51.7206
            ],
            [
              -1.1936,
              51.7206
            ],
            [
              -1.1936,
              51.7185
            ],
            [
              -1.1982,
              51.7185
            ],
            [
              -1.1982,
              51.7206
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-27T19:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.7206,
      "etrUpdate": true
    },
    {
      "latitude": 57.40437293344397,
      "type": "HV",
      "reference": "KM5648",
      "etaUpdate": true,
      "affectedCustomerCount": 26,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "d91aa59f-4cbb-4706-bb2a-a468245e8522",
      "minLongitude": -2.3928,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.3590350683794026,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-27T13:38:00.000+0000",
      "estimatedRestoration": "2023-01-27T22:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KM5648'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KM5648",
      "maxLongitude": -2.3447,
      "minLatitude": 57.3932,
      "name": "AB51 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "AB51 8SN",
        "AB51 8SP",
        "AB51 8SQ",
        "AB51 8SR",
        "AB51 8TP"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.3928,
              57.4223
            ],
            [
              -2.3447,
              57.4223
            ],
            [
              -2.3447,
              57.3932
            ],
            [
              -2.3928,
              57.3932
            ],
            [
              -2.3928,
              57.4223
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-27T14:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 57.4223,
      "etrUpdate": true
    },
    {
      "latitude": 56.41585062642344,
      "type": "PSI",
      "reference": "213732",
      "etaUpdate": true,
      "affectedCustomerCount": 1,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "d46ce536-24ab-48fe-831d-659b7250113e",
      "minLongitude": -3.474,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.4707138602300756,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-27T16:00:00.000+0000",
      "estimatedRestoration": "2023-01-27T22:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '213732'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/213732",
      "maxLongitude": -3.4634,
      "minLatitude": 56.4144,
      "name": "PH1 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PH1 3FX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.474,
              56.4187
            ],
            [
              -3.4634,
              56.4187
            ],
            [
              -3.4634,
              56.4144
            ],
            [
              -3.474,
              56.4144
            ],
            [
              -3.474,
              56.4187
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.4187,
      "etrUpdate": true
    },
    {
      "latitude": 56.65852934921751,
      "type": "HV",
      "reference": "KM5848",
      "etaUpdate": true,
      "affectedCustomerCount": 43,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "a24298ce-3541-444c-9c4e-700dde361b90",
      "minLongitude": -2.6454,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.5957922562992595,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-27T18:34:00.000+0000",
      "estimatedRestoration": "2023-01-27T20:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KM5848'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KM5848",
      "maxLongitude": -2.5561,
      "minLatitude": 56.642,
      "name": "DD11 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DD11 4RY",
        "DD11 4RZ",
        "DD11 4UH",
        "DD9 6UE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6454,
              56.686
            ],
            [
              -2.5561,
              56.686
            ],
            [
              -2.5561,
              56.642
            ],
            [
              -2.6454,
              56.642
            ],
            [
              -2.6454,
              56.686
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.686,
      "etrUpdate": true
    },
    {
      "latitude": 56.47985928148651,
      "type": "LV",
      "reference": "KM5858",
      "etaUpdate": true,
      "affectedCustomerCount": 13,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "5c8be478-bc26-456b-ac21-07d881dce59e",
      "minLongitude": -3.0244,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.0214358617502874,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-27T19:01:00.000+0000",
      "estimatedRestoration": "2023-01-27T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KM5858'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KM5858",
      "maxLongitude": -3.0189,
      "minLatitude": 56.4789,
      "name": "DD2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DD2 2SG",
        "DD2 2SR",
        "DD2 2SS",
        "DD2 2SU",
        "DD2 2SX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.0244,
              56.4817
            ],
            [
              -3.0189,
              56.4817
            ],
            [
              -3.0189,
              56.4789
            ],
            [
              -3.0244,
              56.4789
            ],
            [
              -3.0244,
              56.4817
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-27T20:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.4817,
      "etrUpdate": true
    }
  ]
}
