{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T08:00:00.000+0000",
      "latitude": 51.45257987985995,
      "estimatedRestoration": "2022-02-04T16:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '204866'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/204866",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.45356,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.68752
            },
            {
              "py/object": "Point",
              "latitude": 51.45208,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.68389
            },
            {
              "py/object": "Point",
              "latitude": 51.45035,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.6827
            },
            {
              "py/object": "Point",
              "latitude": 51.45356,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.68752
            }
          ],
          "subCodes": [
            "SL4 4PX",
            "SL4 4RZ",
            "SL4 4SS"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "204866",
      "name": "SL4 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SL4 4PX",
        "SL4 4RZ",
        "SL4 4SS"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.68752,
              51.45356
            ],
            [
              -0.68389,
              51.45208
            ],
            [
              -0.6827,
              51.45035
            ],
            [
              -0.68752,
              51.45356
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "d52af19e-9a7b-418b-b0db-8b44783efd69",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6854456018673009,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T08:30:00.000+0000",
      "latitude": 50.737124395878055,
      "estimatedRestoration": "2022-02-04T15:30:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '205351'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/205351",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.73629,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.88638
            },
            {
              "py/object": "Point",
              "latitude": 50.73793,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.88293
            },
            {
              "py/object": "Point",
              "latitude": 50.73802,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.88118
            },
            {
              "py/object": "Point",
              "latitude": 50.73607,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.88368
            },
            {
              "py/object": "Point",
              "latitude": 50.73629,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.88638
            }
          ],
          "subCodes": [
            "BH3 7BD",
            "BH3 7BG",
            "BH3 7EN",
            "BH3 7HR",
            "BH3 7HX"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "205351",
      "name": "BH3 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BH3 7BD",
        "BH3 7BG",
        "BH3 7EN",
        "BH3 7HR",
        "BH3 7HX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.88638,
              50.73629
            ],
            [
              -1.88293,
              50.73793
            ],
            [
              -1.88118,
              50.73802
            ],
            [
              -1.88368,
              50.73607
            ],
            [
              -1.88638,
              50.73629
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "da6e6b9d-0b5b-4806-b60e-2defec941cb0",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.8835062703507504,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T09:00:00.000+0000",
      "latitude": 51.372475909729964,
      "estimatedRestoration": "2022-02-04T15:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '205082'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/205082",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.37421,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.94911
            },
            {
              "py/object": "Point",
              "latitude": 51.372475909729964,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.9488508681926535
            },
            {
              "py/object": "Point",
              "latitude": 51.37159,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.94814
            },
            {
              "py/object": "Point",
              "latitude": 51.37421,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.94911
            }
          ],
          "subCodes": [
            "SN10 2JT",
            "SN10 2RZ"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "205082",
      "name": "SN10 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN10 2JT",
        "SN10 2RZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.94911,
              51.37421
            ],
            [
              -1.9488508681926535,
              51.372475909729964
            ],
            [
              -1.94814,
              51.37159
            ],
            [
              -1.94911,
              51.37421
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "325432eb-ed8f-4621-85d8-a0736da44c87",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.9488508681926535,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T09:33:00.000+0000",
      "latitude": 51.62920224023422,
      "estimatedRestoration": "2022-02-04T21:30:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7566'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7566",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.62932,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.74933
            },
            {
              "py/object": "Point",
              "latitude": 51.62920224023422,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.7490757793696934
            },
            {
              "py/object": "Point",
              "latitude": 51.62916,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.74894
            },
            {
              "py/object": "Point",
              "latitude": 51.62923,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.74887
            },
            {
              "py/object": "Point",
              "latitude": 51.62954,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.74857
            },
            {
              "py/object": "Point",
              "latitude": 51.62932,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.74933
            }
          ],
          "subCodes": [
            "HP13 6BF",
            "HP13 6TA",
            "HP13 6TH",
            "HP13 6TQ"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JK7566",
      "name": "HP13 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "HP13 6BF",
        "HP13 6TA",
        "HP13 6TH",
        "HP13 6TQ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.74933,
              51.62932
            ],
            [
              -0.7490757793696934,
              51.62920224023422
            ],
            [
              -0.74894,
              51.62916
            ],
            [
              -0.74887,
              51.62923
            ],
            [
              -0.74857,
              51.62954
            ],
            [
              -0.74933,
              51.62932
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-02-04T10:30:00.000+0000",
      "UUID": "cd8601a7-defc-40be-a56c-aa99897618ce",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7490757793696934,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T09:49:00.000+0000",
      "latitude": 50.78865566244307,
      "estimatedRestoration": "2022-02-04T20:00:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7595'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7595",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.78952,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.97258
            },
            {
              "py/object": "Point",
              "latitude": 50.78806,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.97176
            },
            {
              "py/object": "Point",
              "latitude": 50.78824,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.97126
            },
            {
              "py/object": "Point",
              "latitude": 50.78869,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.97058
            },
            {
              "py/object": "Point",
              "latitude": 50.78907,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.97148
            },
            {
              "py/object": "Point",
              "latitude": 50.78952,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.97258
            }
          ],
          "subCodes": [
            "PO11 9BU",
            "PO11 9JX",
            "PO11 9NN",
            "PO11 9NW",
            "PO11 9PW",
            "PO11 9PX"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JK7595",
      "engineerOnSiteTime": "2022-02-04T10:30:00.000+0000",
      "name": "PO11 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO11 9BU",
        "PO11 9JX",
        "PO11 9NN",
        "PO11 9NW",
        "PO11 9PW",
        "PO11 9PX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.97258,
              50.78952
            ],
            [
              -0.97176,
              50.78806
            ],
            [
              -0.97126,
              50.78824
            ],
            [
              -0.97058,
              50.78869
            ],
            [
              -0.97148,
              50.78907
            ],
            [
              -0.97258,
              50.78952
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "0d4c2468-73e6-4334-bae9-f2930d7f363e",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9715637474613836,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T13:08:00.000+0000",
      "latitude": 51.43350753519206,
      "estimatedRestoration": "2022-02-04T16:30:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7781'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7781",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.43358,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.96244
            },
            {
              "py/object": "Point",
              "latitude": 51.43335,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.96104
            },
            {
              "py/object": "Point",
              "latitude": 51.43309,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.9594
            },
            {
              "py/object": "Point",
              "latitude": 51.43279,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.95712
            },
            {
              "py/object": "Point",
              "latitude": 51.43285,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.9543
            },
            {
              "py/object": "Point",
              "latitude": 51.43513,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.96242
            },
            {
              "py/object": "Point",
              "latitude": 51.43358,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.96244
            }
          ],
          "subCodes": [
            "RG2 7JR",
            "RG2 7JS",
            "RG2 7JX",
            "RG2 7LN",
            "RG2 7LW",
            "RG2 7PL",
            "RG2 7PX",
            "RG2 7RX",
            "RG2 7RY",
            "RG2 7RZ"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JK7781",
      "name": "RG2 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG2 7JR",
        "RG2 7JS",
        "RG2 7JX",
        "RG2 7LN",
        "RG2 7LW",
        "RG2 7PL",
        "RG2 7PX",
        "RG2 7RX",
        "RG2 7RY",
        "RG2 7RZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.96244,
              51.43358
            ],
            [
              -0.96104,
              51.43335
            ],
            [
              -0.9594,
              51.43309
            ],
            [
              -0.95712,
              51.43279
            ],
            [
              -0.9543,
              51.43285
            ],
            [
              -0.96242,
              51.43513
            ],
            [
              -0.96244,
              51.43358
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-02-04T14:00:00.000+0000",
      "UUID": "91b89527-0e84-42d2-b098-8bb543f8dd01",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9593396881753854,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T12:59:00.000+0000",
      "latitude": 50.91355645789587,
      "estimatedRestoration": "2022-02-04T16:30:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7774'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7774",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.91396,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.44288
            },
            {
              "py/object": "Point",
              "latitude": 50.91332,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.43875
            },
            {
              "py/object": "Point",
              "latitude": 50.91335,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.43693
            },
            {
              "py/object": "Point",
              "latitude": 50.91355645789587,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.4394932569586298
            },
            {
              "py/object": "Point",
              "latitude": 50.91396,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.44288
            }
          ],
          "subCodes": [
            "SO15 0HW",
            "SO15 8PN",
            "SO15 8RR"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JK7774",
      "name": "SO15 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO15 0HW",
        "SO15 8PN",
        "SO15 8RR"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.44288,
              50.91396
            ],
            [
              -1.43875,
              50.91332
            ],
            [
              -1.43693,
              50.91335
            ],
            [
              -1.4394932569586298,
              50.91355645789587
            ],
            [
              -1.44288,
              50.91396
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-02-04T14:00:00.000+0000",
      "UUID": "2bedf020-78a6-4f07-877b-d6b978f2c72a",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.4394932569586298,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T12:52:00.000+0000",
      "latitude": 51.51041373608466,
      "estimatedRestoration": "2022-02-04T17:30:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7768'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7768",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.51187,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75961
            },
            {
              "py/object": "Point",
              "latitude": 51.51256,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75847
            },
            {
              "py/object": "Point",
              "latitude": 51.50526,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75107
            },
            {
              "py/object": "Point",
              "latitude": 51.51187,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75961
            }
          ],
          "subCodes": [
            "SL6 3AF",
            "SL6 3PJ",
            "SL6 3PL",
            "SL6 3PP"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JK7768",
      "name": "SL6 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SL6 3AF",
        "SL6 3PJ",
        "SL6 3PL",
        "SL6 3PP"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.75961,
              51.51187
            ],
            [
              -0.75847,
              51.51256
            ],
            [
              -0.75107,
              51.50526
            ],
            [
              -0.75961,
              51.51187
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-02-04T14:15:00.000+0000",
      "UUID": "69c04eee-28a9-47ba-941e-a6b3c3f08c37",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7569427337555136,
      "resolved": false
    },
    {
      "customIncludeDefault": false,
      "py/object": "Fault",
      "loggedAt": "2022-01-29T07:49:00.000+0000",
      "latitude": 57.13118332204541,
      "estimatedRestoration": "2022-02-03T23:59:00.000+0000",
      "message": "Weâ€™re very sorry for the power cut. Our teams are working hard to restore your power, however, due to weather conditions which have impacted our network, itâ€™s taking longer than normal to restore supplies. You can continue to track the progress of your power cut here.<br/><br/>If you are in need of extra support, such as requiring electricity for medical equipment, you can call us on 105 where our teams will be on hand to help.<br/><br/>For information on welfare provisions and latest updates on our response to the weather, please <a href=\"http://news.ssen.co.uk/news/all-articles/2022/january/storm-malik-update/\" target=\"_blank\">click here</a>.<br/><br/>Thank you for your ongoing patience.",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK0358",
      "reference": "JK0358",
      "name": "AB34 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "AB34 4TA"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.8430014147241986,
          57.13118332204541
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-01-29T08:45:00.000+0000",
      "UUID": "e23736ee-753d-40b5-8565-6af895fd2ed0",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.8430014147241986,
      "resolved": false
    },
    {
      "customIncludeDefault": false,
      "py/object": "Fault",
      "loggedAt": "2022-01-29T11:03:00.000+0000",
      "latitude": 57.22234403711243,
      "estimatedRestoration": "2022-02-04T15:00:00.000+0000",
      "message": "Weâ€™re very sorry for the power cut. Our teams are working hard to restore your power, however, due to weather conditions which have impacted our network, itâ€™s taking longer than normal to restore supplies. You can continue to track the progress of your power cut here.<br/><br/>If you are in need of extra support, such as requiring electricity for medical equipment, you can call us on 105 where our teams will be on hand to help.<br/><br/>For information on welfare provisions and latest updates on our response to the weather, please <a href=\"http://news.ssen.co.uk/news/all-articles/2022/january/storm-malik-update/\" target=\"_blank\">click here</a>.<br/><br/>Thank you for your ongoing patience.",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK2170",
      "reference": "JK2170",
      "name": "AB21 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "AB21 0TF"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.277759473144684,
          57.22234403711243
        ],
        "type": "Point"
      },
      "UUID": "ee5eef0d-daf0-45ea-b512-cc70dfed95dd",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.277759473144684,
      "resolved": false
    },
    {
      "customIncludeDefault": false,
      "py/object": "Fault",
      "loggedAt": "2022-01-30T20:06:00.000+0000",
      "latitude": 57.10744455283372,
      "estimatedRestoration": "2022-02-04T16:00:00.000+0000",
      "message": "Weâ€™re very sorry for the power cut. Our teams are working hard to restore your power, however, due to weather conditions which have impacted our network, itâ€™s taking longer than normal to restore supplies. You can continue to track the progress of your power cut here.<br/><br/>If you are in need of extra support, such as requiring electricity for medical equipment, you can call us on 105 where our teams will be on hand to help.<br/><br/>For information on welfare provisions and latest updates on our response to the weather, please <a href=\"http://news.ssen.co.uk/news/all-articles/2022/january/storm-malik-update/\" target=\"_blank\">click here</a>.<br/><br/>Thank you for your ongoing patience.",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK2668",
      "reference": "JK2668",
      "name": "AB14 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "AB14 0NT",
        "AB14 0NW",
        "AB14 0NX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.2807120574833997,
          57.10744455283372
        ],
        "type": "Point"
      },
      "UUID": "ed3d86f9-857c-4561-9d87-c281e2610fb6",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "evChargersAffected": [
        "2bc8e25b-b2d4-4a3f-bc6b-24e40fd21640",
        "80205bb4-aa4d-4db1-a3fa-668057c95688"
      ],
      "longitude": -2.2807120574833997,
      "resolved": false
    },
    {
      "customIncludeDefault": false,
      "py/object": "Fault",
      "loggedAt": "2022-02-01T10:48:00.000+0000",
      "latitude": 57.035842119420344,
      "estimatedRestoration": "2022-02-03T23:59:00.000+0000",
      "message": "Weâ€™re very sorry for the power cut. Our teams are working hard to restore your power, however, due to weather conditions which have impacted our network, itâ€™s taking longer than normal to restore supplies. You can continue to track the progress of your power cut here.<br/><br/>If you are in need of extra support, such as requiring electricity for medical equipment, you can call us on 105 where our teams will be on hand to help.<br/><br/>For information on welfare provisions and latest updates on our response to the weather, please <a href=\"http://news.ssen.co.uk/news/all-articles/2022/january/storm-malik-update/\" target=\"_blank\">click here</a>.<br/><br/>Thank you for your ongoing patience.",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK6700",
      "reference": "JK6700",
      "name": "AB35 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "AB35 5SP"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.0572431479847304,
          57.035842119420344
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-02-03T14:30:00.000+0000",
      "UUID": "ddb9ba99-f30e-49ac-a855-5f146bba29d2",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.0572431479847304,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-03T17:55:00.000+0000",
      "latitude": 56.95603174502909,
      "estimatedRestoration": "2022-02-04T13:00:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7280'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7280",
      "reference": "JK7280",
      "name": "AB39 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "AB39 3XE"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.28100231983939,
          56.95603174502909
        ],
        "type": "Point"
      },
      "UUID": "3c169aee-dc4e-4564-a05f-e52d0a889693",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.28100231983939,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-29T09:00:00.000+0000",
      "latitude": 57.07173020188329,
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK0345'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK0345",
      "reference": "JK0345",
      "name": "AB35 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "AB35 5SD"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.970912657029245,
          57.07173020188329
        ],
        "type": "Point"
      },
      "UUID": "6c0b3cd8-d2d0-4104-9f0c-ed2eb63b5468",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.970912657029245,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T10:53:00.000+0000",
      "latitude": 56.736861713925535,
      "estimatedRestoration": "2022-02-04T17:00:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7657'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7657",
      "reference": "JK7657",
      "name": "DD9 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "DD9 6BP",
        "DD9 6BU"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.661288417196979,
          56.736861713925535
        ],
        "type": "Point"
      },
      "UUID": "d6cb4b27-43ce-4720-98c0-6ad0accb1c5a",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.661288417196979,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T09:58:00.000+0000",
      "latitude": 56.367735473372946,
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7593'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7593",
      "reference": "JK7593",
      "name": "FK15 & FK20 Areas",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "FK15 0LX",
        "FK20 8QN",
        "FK20 8QP",
        "FK20 8QR",
        "FK20 8QW",
        "FK20 8RJ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -4.494659890266438,
          56.367735473372946
        ],
        "type": "Point"
      },
      "UUID": "5360b18c-ccb6-40fc-9e0b-c8419e00da4b",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -4.494659890266438,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T11:00:00.000+0000",
      "latitude": 56.382863553594184,
      "estimatedRestoration": "2022-02-04T14:00:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7568'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7568",
      "reference": "JK7568",
      "name": "PA33 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PA33 1AA",
        "PA33 1AF",
        "PA33 1AH",
        "PA33 1AJ",
        "PA33 1AN",
        "PA33 1AP",
        "PA33 1AQ",
        "PA33 1BP"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -5.068365614013036,
          56.382863553594184
        ],
        "type": "Point"
      },
      "UUID": "2749c64c-3c2c-4ffd-bcff-6fc3be926f7d",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.068365614013036,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T07:36:00.000+0000",
      "latitude": 57.48038222453356,
      "estimatedRestoration": "2022-02-04T16:30:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7494'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7494",
      "reference": "JK7494",
      "engineerOnSiteTime": "2022-02-04T08:30:00.000+0000",
      "name": "IV1 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV1 1LG",
        "IV1 1LR",
        "IV1 1NH",
        "IV1 1NW"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -4.224160207427263,
          57.48038222453356
        ],
        "type": "Point"
      },
      "UUID": "3f4cec45-9c3e-425a-a599-b7264a6496bf",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -4.224160207427263,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T10:58:00.000+0000",
      "latitude": 57.38860576139354,
      "estimatedRestoration": "2022-02-04T16:00:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7722'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7722",
      "reference": "JK7722",
      "name": "HS8 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "HS8 5NU",
        "HS8 5PD",
        "HS8 5PE",
        "HS8 5QX",
        "HS8 5QY",
        "HS8 5RA",
        "HS8 5RH",
        "HS8 5RJ",
        "HS8 5RL",
        "HS8 5RQ",
        "HS8 5RU"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -7.330714222665429,
          57.38860576139354
        ],
        "type": "Point"
      },
      "UUID": "8786c296-a231-4f88-9743-f6db35406316",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -7.330714222665429,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T13:33:00.000+0000",
      "latitude": 56.373571524461724,
      "estimatedRestoration": "2022-02-04T17:00:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7800'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7800",
      "reference": "JK7800",
      "name": "PA69 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PA69 6ES",
        "PA69 6EU"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -6.088765977436206,
          56.373571524461724
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-02-04T15:00:00.000+0000",
      "UUID": "9efad357-78b3-4fd2-b920-d34ef4d17b4e",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -6.088765977436206,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-04T14:01:00.000+0000",
      "latitude": 57.540409813593776,
      "estimatedRestoration": "2022-02-04T17:00:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JK7818'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JK7818",
      "reference": "JK7818",
      "name": "IV8 & IV6 Areas",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV6 7RY",
        "IV6 7RZ",
        "IV8 8NP"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -4.309894199805716,
          57.540409813593776
        ],
        "type": "Point"
      },
      "UUID": "c1610d55-a6c9-4614-b509-74e031c94d5e",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -4.309894199805716,
      "resolved": false
    }
  ]
}
