{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-08T08:00:00.000+0000",
      "latitude": 51.69744786236073,
      "estimatedRestoration": "2022-05-13T14:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '207623'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/207623",
      "reference": "207623",
      "name": "GL7 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GL7 4BT",
        "GL7 4BX",
        "GL7 4BY",
        "GL7 4DD",
        "GL7 4DE",
        "GL7 4DW"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.7807073353127607,
          51.69744786236073
        ],
        "type": "Point"
      },
      "UUID": "965dca83-b96b-4574-a39e-023b6d218f36",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7807073353127607,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T08:00:00.000+0000",
      "latitude": 51.06367022795957,
      "estimatedRestoration": "2022-05-12T13:30:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '207374'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/207374",
      "reference": "207374",
      "name": "SO20 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO20 6NA"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.5325816161313135,
          51.06367022795957
        ],
        "type": "Point"
      },
      "UUID": "0d6206bd-2c90-46ae-b3a0-2623537468e4",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.5325816161313135,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T08:00:00.000+0000",
      "latitude": 51.06367022795957,
      "estimatedRestoration": "2022-05-12T13:30:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '207375'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/207375",
      "reference": "207375",
      "name": "SO20 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO20 6NA"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.5325816161313135,
          51.06367022795957
        ],
        "type": "Point"
      },
      "UUID": "871102f1-c86b-4a0a-904b-c64dd4e37380",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.5325816161313135,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T08:09:00.000+0000",
      "latitude": 51.63427948705722,
      "estimatedRestoration": "2022-05-10T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9295'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9295",
      "reference": "JS9295",
      "engineerOnSiteTime": "2022-05-10T09:15:00.000+0000",
      "name": "HP13 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "HP13 6SR",
        "HP13 6ST",
        "HP13 6TB",
        "HP13 6TE",
        "HP13 6TF",
        "HP13 6XA",
        "HP13 6XB"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.7496296982889934,
          51.63427948705722
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-10T09:00:00.000+0000",
      "UUID": "e1332b95-9be4-4121-b687-0b318364164e",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7496296982889934,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T11:14:00.000+0000",
      "latitude": 51.41111798709461,
      "estimatedRestoration": "2022-05-10T19:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9451'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9451",
      "reference": "JS9451",
      "name": "RG41 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG41 4SA",
        "RG41 4SG",
        "RG41 4SH",
        "RG41 4SJ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.8765805066587821,
          51.41111798709461
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-10T15:30:00.000+0000",
      "UUID": "e0b0d66c-8007-429e-8412-155595740a3b",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "evChargersAffected": [
        "ecddc4c7-c58d-4b2d-a3e8-acff7a234f7e",
        "b5be9fc8-26b7-4c9e-8556-61cf3fc80128",
        "200afcb6-538d-4884-aede-a8411ecc2c7f",
        "878a4515-1c8c-460b-b006-a64a32b7dedb",
        "ca2179fb-86d5-49a7-aed0-e194b6be9708",
        "2363d763-4851-4fcd-a8b7-1ac5adbeef78",
        "d2d35ea2-eb7f-45d4-b6a5-dd8e9ffcbeb6",
        "cc3fe1ff-0f5d-4717-8a0c-c1c0c05f461d",
        "a746970e-d117-4d65-949a-fbd7d02a5a3d",
        "106d6b0e-1207-4568-9daf-bd3c6cb73e8d",
        "2cb31782-3d76-4ab2-ad4b-b00f6ec140b1",
        "6335822e-cd6d-4098-9f4e-14c2ec1efaaf"
      ],
      "longitude": -0.8765805066587821,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T12:25:00.000+0000",
      "latitude": 50.94518964394923,
      "estimatedRestoration": "2022-05-10T19:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9490'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9490",
      "reference": "JS9490",
      "name": "BA20 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BA10 0PT",
        "BA20",
        "BA20 1EH",
        "BA20 1EL",
        "BA20 1FA",
        "BA20 1LA",
        "BA20 1LF",
        "BA20 1LT",
        "BA20 1LX",
        "BA20 1LY",
        "BA20 1NH",
        "BA20 1NL",
        "BA20 1NN",
        "BA20 1NP",
        "BA20 1NR",
        "BA20 1NU",
        "BA20 1NY",
        "BA20 1NZ",
        "BA20 1PE",
        "BA20 1PF",
        "BA20 1PG",
        "BA20 1PN",
        "BA20 1PQ",
        "BA20 1QF",
        "BA20 1QG",
        "BA20 1QN",
        "BA20 1QP",
        "BA20 1QQ",
        "BA20 1QR",
        "BA20 1QW",
        "BA20 1RY",
        "BA20 1SB",
        "BA20 1SF",
        "BA20 1SX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.624596845056998,
          50.94518964394923
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-10T16:00:00.000+0000",
      "UUID": "026f5c37-e83d-4427-b8ea-c183c5350934",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "evChargersAffected": [
        "d60caecc-b6af-4b3d-9f2c-afdfdf971cc9",
        "82995f12-658e-4bab-9f36-7b473b6dda5b",
        "13b27dc7-7df1-4c3a-94ab-9d53295c7822"
      ],
      "longitude": -2.624596845056998,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T15:35:00.000+0000",
      "latitude": 51.758006418316086,
      "estimatedRestoration": "2022-05-10T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9439'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9439",
      "reference": "JS9439",
      "engineerOnSiteTime": "2022-05-10T11:41:00.000+0000",
      "name": "OX2 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "OX2 9NS"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.347506619996003,
          51.758006418316086
        ],
        "type": "Point"
      },
      "UUID": "19a7900c-9c91-4353-9163-5d3ee8d3368b",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.347506619996003,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T13:41:00.000+0000",
      "latitude": 51.08436718445452,
      "estimatedRestoration": "2022-05-10T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9562'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9562",
      "reference": "JS9562",
      "engineerOnSiteTime": "2022-05-10T14:30:00.000+0000",
      "name": "SP1 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SP1 3EG",
        "SP1 3EQ",
        "SP1 3HX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.7789894829841775,
          51.08436718445452
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-10T14:30:00.000+0000",
      "UUID": "19b09863-cb5a-49d4-86ae-71856672f6b2",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7789894829841775,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T14:40:00.000+0000",
      "latitude": 51.43788110159321,
      "estimatedRestoration": "2022-05-10T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9517'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9517",
      "reference": "JS9517",
      "engineerOnSiteTime": "2022-05-10T14:40:00.000+0000",
      "name": "TW13 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "TW13 6DH"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.3855684695033329,
          51.43788110159321
        ],
        "type": "Point"
      },
      "UUID": "57772406-1066-47e6-90d4-12a17c12730f",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.3855684695033329,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T14:23:00.000+0000",
      "latitude": 50.79187510814957,
      "estimatedRestoration": "2022-05-10T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9588'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9588",
      "reference": "JS9588",
      "engineerOnSiteTime": "2022-05-10T15:30:00.000+0000",
      "name": "PO22 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO22 7PX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.6288240626967219,
          50.79187510814957
        ],
        "type": "Point"
      },
      "UUID": "0f3126ef-a299-456e-ba08-9ea84397b8c3",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6288240626967219,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T12:42:00.000+0000",
      "latitude": 50.712213060910386,
      "estimatedRestoration": "2022-05-10T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9510'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9510",
      "reference": "JS9510",
      "name": "DT1 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT1 1AL",
        "DT1 1NH",
        "DT1 1NJ",
        "DT1 1NN",
        "DT1 1PA",
        "DT1 1PE"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.4237158142262434,
          50.712213060910386
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-10T16:30:00.000+0000",
      "UUID": "db9232fb-8182-4f26-8a72-f948389fd100",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.4237158142262434,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T16:13:00.000+0000",
      "latitude": 51.2322661014009,
      "estimatedRestoration": "2022-05-10T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9629'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9629",
      "reference": "JS9629",
      "name": "BA11 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BA11 3HH",
        "BA11 3HJ",
        "BA11 3HN",
        "BA11 3HR",
        "BA11 3HS",
        "BA11 3HW",
        "BA11 3JE",
        "BA11 3JF",
        "BA11 3JH",
        "BA11 4JE"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.338217225737076,
          51.2322661014009
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-10T17:30:00.000+0000",
      "UUID": "58d58f4a-cedc-4265-a015-8e968b0634ef",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.338217225737076,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T17:16:00.000+0000",
      "latitude": 51.15379285442399,
      "estimatedRestoration": "2022-05-10T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9651'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9651",
      "reference": "JS9651",
      "name": "GU34 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU34 2EF",
        "GU34 2EG",
        "GU34 2EN",
        "GU34 2EQ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.9821291628843277,
          51.15379285442399
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-10T17:50:00.000+0000",
      "UUID": "8c6903e6-ea8a-455b-abf9-14dd5e1b046d",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9821291628843277,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T12:07:00.000+0000",
      "latitude": 56.41556577183446,
      "estimatedRestoration": "2022-05-10T19:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9475'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9475",
      "reference": "JS9475",
      "engineerOnSiteTime": "2022-05-10T12:20:00.000+0000",
      "name": "PA34 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PA34 5DT",
        "PA34 5DY",
        "PA34 5DZ",
        "PA34 5EA",
        "PA34 5ED",
        "PA34 5TN"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -5.465357754637308,
          56.41556577183446
        ],
        "type": "Point"
      },
      "UUID": "598ef147-9fb9-41b4-b1c0-5155cf8cbace",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.465357754637308,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-10T17:53:00.000+0000",
      "latitude": 58.53202237115596,
      "estimatedRestoration": "2022-05-10T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS9658'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS9658",
      "reference": "JS9658",
      "name": "KW1 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "KW1 4TP"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.2709123194789034,
          58.53202237115596
        ],
        "type": "Point"
      },
      "UUID": "8cb88db2-2bf4-4ddf-a469-83801f1b18ab",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.2709123194789034,
      "resolved": false
    }
  ]
}
