{
  "Faults": [
    {
      "latitude": 51.55328524587392,
      "type": "LV",
      "reference": "KN6378",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-15T16:10:00.000+0000",
      "affectedCustomerCount": 13,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "25b871c0-4129-4221-9f94-46c99daf4b1a",
      "minLongitude": -1.8484,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.8450490744354262,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-15T17:28:00.000+0000",
      "estimatedRestoration": "2023-02-16T11:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN6378'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN6378",
      "maxLongitude": -1.8432,
      "minLatitude": 51.5525,
      "name": "SN5 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN5 6BL",
        "SN5 6ED",
        "SN5 6EE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.8484,
              51.5544
            ],
            [
              -1.8432,
              51.5544
            ],
            [
              -1.8432,
              51.5525
            ],
            [
              -1.8484,
              51.5525
            ],
            [
              -1.8484,
              51.5544
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-15T16:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5544,
      "etrUpdate": true
    },
    {
      "latitude": 51.28371224382871,
      "type": "HV",
      "reference": "KN6550",
      "etaUpdate": true,
      "affectedCustomerCount": 2,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "3f7bdc29-3d28-4477-acf2-32a0b570c036",
      "minLongitude": -1.0935,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0926090704770965,
      "resolved": false,
      "py/object": "Fault",
      "Messages": [
        {
          "py/object": "Message",
          "senderName": "tobias.sell@sse.com",
          "senderUserId": "44833855-d575-41a0-92f7-7cd8a3b8dabd",
          "text": "Engineers are responding to a main network fault in the area. We aim to restore power by 01:30.",
          "UUID": "a8cc4a21-2f54-410d-aaf7-a5300c46fa74",
          "py/class": "http://opengrid.com/givr/1.0#//Message",
          "sentDateTime": "2023-02-15T22:48:07.455+0000"
        }
      ],
      "srtUpdate": true,
      "loggedAt": "2023-02-15T22:25:00.000+0000",
      "estimatedRestoration": "2023-02-16T10:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN6550'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN6550",
      "maxLongitude": -1.0891,
      "minLatitude": 51.2831,
      "name": "RG24 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG24 9DX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0935,
              51.2847
            ],
            [
              -1.0891,
              51.2847
            ],
            [
              -1.0891,
              51.2831
            ],
            [
              -1.0935,
              51.2831
            ],
            [
              -1.0935,
              51.2847
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.2847,
      "etrUpdate": true
    },
    {
      "latitude": 51.58331544836443,
      "type": "LV",
      "reference": "KN6524",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-15T22:30:00.000+0000",
      "affectedCustomerCount": 34,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "0df8e3bb-7709-41b0-ac95-4f20747211c4",
      "minLongitude": -2.101,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.097068301584844,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-15T20:49:00.000+0000",
      "estimatedRestoration": "2023-02-16T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN6524'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN6524",
      "maxLongitude": -2.0942,
      "minLatitude": 51.5811,
      "name": "SN16 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN16 0AG",
        "SN16 9AS",
        "SN16 9AT",
        "SN16 9AU",
        "SN16 9AX",
        "SN16 9AZ",
        "SN16 9BD",
        "SN16 9BE",
        "SN16 9BG",
        "SN16 9BH",
        "SN16 9BQ",
        "SN16 9BU",
        "SN16 9BY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.101,
              51.5858
            ],
            [
              -2.0942,
              51.5858
            ],
            [
              -2.0942,
              51.5811
            ],
            [
              -2.101,
              51.5811
            ],
            [
              -2.101,
              51.5858
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-15T22:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5858,
      "etrUpdate": true
    },
    {
      "latitude": 51.28274056281743,
      "type": "HV",
      "reference": "KN6586",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-16T01:45:00.000+0000",
      "affectedCustomerCount": 16,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "52dc1de4-4bfe-4334-8b39-75b6e4959734",
      "minLongitude": -2.0036,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.9975992184562663,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-16T00:47:00.000+0000",
      "estimatedRestoration": "2023-02-16T09:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN6586'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN6586",
      "maxLongitude": -1.9896,
      "minLatitude": 51.2806,
      "name": "SN10 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN10 4BE",
        "SN10 4BQ",
        "SN10 4EU",
        "SN10 4EY",
        "SN10 4HJ",
        "SN10 4HL",
        "SN10 4HN",
        "SN10 4HP",
        "SN10 4HQ",
        "SN10 4HW",
        "SN10 4HX",
        "SN10 4HZ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.0036,
              51.2858
            ],
            [
              -1.9896,
              51.2858
            ],
            [
              -1.9896,
              51.2806
            ],
            [
              -2.0036,
              51.2806
            ],
            [
              -2.0036,
              51.2858
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-16T02:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.2858,
      "etrUpdate": true
    },
    {
      "latitude": 51.17382206118972,
      "type": "LV",
      "reference": "KN6646",
      "etaUpdate": true,
      "affectedCustomerCount": 2,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "b94f10f6-ab04-4c53-b1c1-0c9012a20500",
      "minLongitude": -1.5909,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.5770717957673581,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-16T04:16:00.000+0000",
      "estimatedRestoration": "2023-02-16T09:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN6646'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN6646",
      "maxLongitude": -1.5695,
      "minLatitude": 51.1669,
      "name": "SP11 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SP11 8BN",
        "SP11 8RX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.5909,
              51.1799
            ],
            [
              -1.5695,
              51.1799
            ],
            [
              -1.5695,
              51.1669
            ],
            [
              -1.5909,
              51.1669
            ],
            [
              -1.5909,
              51.1799
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-16T06:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.1799,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-16T06:15:00.000+0000",
      "latitude": 50.768723232117445,
      "estimatedRestoration": "2023-02-16T10:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN6682'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN6682",
      "reference": "KN6682",
      "etaUpdate": true,
      "affectedCustomerCount": 6,
      "name": "BH23 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BH23 8JL",
        "BH23 8JY",
        "BH23 8JZ"
      ],
      "location": {
        "coordinates": [
          -1.7266493932518263,
          50.768723232117445
        ],
        "type": "Point"
      },
      "UUID": "134e6883-cfd2-41f3-a6b8-29722cc84bee",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "etrUpdate": true,
      "longitude": -1.7266493932518263,
      "resolved": false
    }
  ]
}
