{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-17T15:21:00.000+0000",
      "latitude": 51.29421892459066,
      "estimatedRestoration": "2022-05-18T07:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT3391'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT3391",
      "reference": "JT3391",
      "name": "SP11 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SP11 9HD",
        "SP11 9HE"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.5264164995069407,
          51.29421892459066
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-17T16:20:00.000+0000",
      "UUID": "9c017843-a941-4023-b952-c38941ede062",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.5264164995069407,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-17T21:50:00.000+0000",
      "latitude": 51.564515002975874,
      "estimatedRestoration": "2022-05-18T06:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT3564'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT3564",
      "reference": "JT3564",
      "engineerOnSiteTime": "2022-05-17T22:45:00.000+0000",
      "name": "SN3 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN3 5DE",
        "SN3 5DY"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.7226881882005394,
          51.564515002975874
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-17T22:59:00.000+0000",
      "UUID": "2489fb29-fe58-4297-8d7a-ed0dabb24cf9",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7226881882005394,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-17T22:35:00.000+0000",
      "latitude": 51.60064046663597,
      "estimatedRestoration": "2022-05-18T10:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT3574'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT3574",
      "reference": "JT3574",
      "engineerOnSiteTime": "2022-05-17T23:40:00.000+0000",
      "name": "SL9 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SL9 8NY"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.5567694140010604,
          51.60064046663597
        ],
        "type": "Point"
      },
      "UUID": "3fe6aba3-7cc9-4e56-9377-66372ebc68cf",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.5567694140010604,
      "resolved": false
    }
  ]
}
