{
  "Faults": [
    {
      "latitude": 51.562813943899585,
      "type": "LV",
      "reference": "KM9414",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-02T22:45:00.000+0000",
      "affectedCustomerCount": 20,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "3ca4f305-333e-4f24-a12d-2e9212b7f5fc",
      "minLongitude": -1.7658,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7629615716913427,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-02T22:03:00.000+0000",
      "estimatedRestoration": "2023-02-03T06:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KM9414'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KM9414",
      "maxLongitude": -1.7608,
      "minLatitude": 51.5618,
      "name": "SN3 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN3 3AX",
        "SN3 3AY",
        "SN3 3BH",
        "SN3 3EF",
        "SN3 3EG",
        "SN3 3EQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.7658,
              51.5641
            ],
            [
              -1.7608,
              51.5641
            ],
            [
              -1.7608,
              51.5618
            ],
            [
              -1.7658,
              51.5618
            ],
            [
              -1.7658,
              51.5641
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-02T22:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5641,
      "etrUpdate": true
    },
    {
      "latitude": 50.8011806168242,
      "type": "LV",
      "reference": "KM9523",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-03T08:35:00.000+0000",
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "79439f37-27b4-4429-b0ed-225a43e0b1b0",
      "minLongitude": -0.8339,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8273948244058972,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-03T07:08:00.000+0000",
      "estimatedRestoration": "2023-02-04T04:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KM9523'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KM9523",
      "maxLongitude": -0.8208,
      "minLatitude": 50.7968,
      "name": "PO20 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO20 7AX",
        "PO20 7BA",
        "PO20 7BB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.8339,
              50.8054
            ],
            [
              -0.8208,
              50.8054
            ],
            [
              -0.8208,
              50.7968
            ],
            [
              -0.8339,
              50.7968
            ],
            [
              -0.8339,
              50.8054
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-03T12:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8054,
      "etrUpdate": true
    },
    {
      "latitude": 51.5860411599069,
      "type": "LV",
      "reference": "KM9811",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-03T14:26:00.000+0000",
      "affectedCustomerCount": 17,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "0d80e3af-876c-4486-9ca9-6d3a08e77b1e",
      "minLongitude": -1.8112,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.8087101227654192,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-03T13:57:00.000+0000",
      "estimatedRestoration": "2023-02-04T02:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KM9811'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KM9811",
      "maxLongitude": -1.8051,
      "minLatitude": 51.5852,
      "name": "SN25 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN25 3EG",
        "SN25 3ET",
        "SN25 3EU",
        "SN25 3EX",
        "SN25 3EY",
        "SN25 3EZ",
        "SN25 3HD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.8112,
              51.5873
            ],
            [
              -1.8051,
              51.5873
            ],
            [
              -1.8051,
              51.5852
            ],
            [
              -1.8112,
              51.5852
            ],
            [
              -1.8112,
              51.5873
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-03T14:40:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5873,
      "etrUpdate": true
    },
    {
      "latitude": 50.819124724313056,
      "type": "LV",
      "reference": "KM9972",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-03T17:30:00.000+0000",
      "affectedCustomerCount": 59,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "81fe319b-5ebc-4220-a5cf-faed5216fe6d",
      "minLongitude": -1.0839,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0816808297196332,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-03T16:48:00.000+0000",
      "estimatedRestoration": "2023-02-04T02:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KM9972'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KM9972",
      "maxLongitude": -1.0793,
      "minLatitude": 50.8159,
      "name": "PO2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO2 0BN",
        "PO2 8BJ",
        "PO2 8BL",
        "PO2 8BN",
        "PO2 8BT",
        "PO2 8BW",
        "PO2 8HL",
        "PO2 8NH",
        "PO2 8NJ",
        "PO2 8NL",
        "PO2 8PA",
        "PO2 9AZ",
        "PO2 9BF"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0839,
              50.8229
            ],
            [
              -1.0793,
              50.8229
            ],
            [
              -1.0793,
              50.8159
            ],
            [
              -1.0839,
              50.8159
            ],
            [
              -1.0839,
              50.8229
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8229,
      "etrUpdate": true
    },
    {
      "latitude": 51.235794808300184,
      "type": "LV",
      "reference": "KN0132",
      "etaUpdate": true,
      "affectedCustomerCount": 16,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "cb79abf7-f3d2-4724-b240-d9ac0ccbe51d",
      "minLongitude": -0.8101,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8071144900963666,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-03T21:28:00.000+0000",
      "estimatedRestoration": "2023-02-04T00:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN0132'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN0132",
      "maxLongitude": -0.8049,
      "minLatitude": 51.2342,
      "name": "GU9 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GU9 0DU",
        "GU9 0DX",
        "GU9 0DY",
        "GU9 0JD",
        "GU9 0JE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.8101,
              51.2375
            ],
            [
              -0.8049,
              51.2375
            ],
            [
              -0.8049,
              51.2342
            ],
            [
              -0.8101,
              51.2342
            ],
            [
              -0.8101,
              51.2375
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-03T22:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.2375,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-03T21:30:00.000+0000",
      "latitude": 51.19662916779355,
      "estimatedRestoration": "2023-02-04T04:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN0134'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN0134",
      "reference": "KN0134",
      "etaUpdate": true,
      "affectedCustomerCount": 32,
      "name": "SP4 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SP4 8EP",
        "SP4 8ET",
        "SP4 8JD",
        "SP4 8JE",
        "SP4 8LJ",
        "SP4 8NE",
        "SP4 8NQ"
      ],
      "location": {
        "coordinates": [
          -1.7678630442531744,
          51.19662916779355
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2023-02-03T22:30:00.000+0000",
      "UUID": "c21a1491-c23e-4665-9db0-0017d46a69e8",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "etrUpdate": true,
      "longitude": -1.7678630442531744,
      "resolved": false
    },
    {
      "latitude": 55.78565673154197,
      "type": "HV",
      "reference": "KN0135",
      "etaUpdate": true,
      "affectedCustomerCount": 30,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "89b51a1e-522c-4775-a14b-38da3f5a8cf9",
      "minLongitude": -5.129,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.081088516981686,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-03T21:23:00.000+0000",
      "estimatedRestoration": "2023-02-03T23:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN0135'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN0135",
      "maxLongitude": -5.0253,
      "minLatitude": 55.7573,
      "name": "PA20 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PA20 0QA",
        "PA20 9NA",
        "PA20 9NT",
        "PA20 9NU",
        "PA20 9PE",
        "PA20 9PF"
      ],
      "location": {
        "coordinates": [
          [
            [
              -5.129,
              55.8251
            ],
            [
              -5.0253,
              55.8251
            ],
            [
              -5.0253,
              55.7573
            ],
            [
              -5.129,
              55.7573
            ],
            [
              -5.129,
              55.8251
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-03T21:35:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 55.8251,
      "etrUpdate": true
    }
  ]
}
