{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T13:17:00.000+0000",
      "latitude": 50.733755780047474,
      "estimatedRestoration": "2022-05-22T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5938'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5938",
      "reference": "JT5938",
      "engineerOnSiteTime": "2022-05-22T09:00:00.000+0000",
      "name": "BH15 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BH15 3BT",
        "BH15 3SS",
        "BH15 3SY",
        "BH15 3TB",
        "BH15 3TF"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.9888106406570554,
          50.733755780047474
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-22T13:00:00.000+0000",
      "UUID": "f672409e-5d1a-4730-b061-dfbbd2c29c45",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.9888106406570554,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T12:22:00.000+0000",
      "latitude": 50.850885470089295,
      "estimatedRestoration": "2022-05-22T23:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5988'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5988",
      "reference": "JT5988",
      "engineerOnSiteTime": "2022-05-22T16:15:00.000+0000",
      "name": "PO6 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO6 3JX",
        "PO6 3JZ",
        "PO6 3LA",
        "PO6 3LF"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.0757871890037156,
          50.850885470089295
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-22T13:15:00.000+0000",
      "UUID": "322ad853-d167-4051-b3d9-8610c330dd47",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0757871890037156,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T12:52:00.000+0000",
      "latitude": 50.838969423503904,
      "estimatedRestoration": "2022-05-22T17:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT6017'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT6017",
      "reference": "JT6017",
      "engineerOnSiteTime": "2022-05-22T14:30:00.000+0000",
      "name": "BH24 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BH24 2DS",
        "BH24 2HJ",
        "BH24 2HP",
        "BH24 2HR",
        "BH24 2HT",
        "BH24 2HW",
        "BH24 2JE",
        "BH24 2JG",
        "BH24 2JQ",
        "BH24 2JZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.8412733096937557,
          50.838969423503904
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-22T14:15:00.000+0000",
      "UUID": "c06148d6-3f17-4271-afcc-0f769984a04c",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.8412733096937557,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T11:09:00.000+0000",
      "latitude": 51.49576929553235,
      "estimatedRestoration": "2022-05-22T19:05:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5974'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5974",
      "reference": "JT5974",
      "engineerOnSiteTime": "2022-05-22T12:50:00.000+0000",
      "name": "SL6 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SL6 3LL",
        "SL6 3LU"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.7555691876481939,
          51.49576929553235
        ],
        "type": "Point"
      },
      "UUID": "e38d14d3-1a70-4540-a9a7-733be69f3bcb",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7555691876481939,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T03:06:00.000+0000",
      "latitude": 57.70269172997128,
      "estimatedRestoration": "2022-05-22T14:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5886'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5886",
      "reference": "JT5886",
      "engineerOnSiteTime": "2022-05-22T04:45:00.000+0000",
      "name": "IV17 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV17 0AD",
        "IV17 0AJ",
        "IV17 0AL",
        "IV17 0TS"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -4.230997239871496,
          57.70269172997128
        ],
        "type": "Point"
      },
      "UUID": "5f3a8124-c4c9-4486-ac7b-57a5abd03371",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -4.230997239871496,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T13:59:00.000+0000",
      "latitude": 56.63780947452508,
      "estimatedRestoration": "2022-05-22T19:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT6031'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT6031",
      "reference": "JT6031",
      "name": "DD11 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "DD11 4SP",
        "DD11 4SW",
        "DD11 4TG",
        "DD11 4TJ",
        "DD11 4TQ",
        "DD11 4TX",
        "DD11 4XB",
        "DD11 4XD"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.6604668929582687,
          56.63780947452508
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-22T14:45:00.000+0000",
      "UUID": "ecc60bdc-6296-4615-a1ac-31a790843cd8",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.6604668929582687,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T14:49:00.000+0000",
      "latitude": 57.52230430623112,
      "estimatedRestoration": "2022-05-22T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT6045'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT6045",
      "reference": "JT6045",
      "name": "IV2 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV2 7JG",
        "IV2 7JJ",
        "IV2 7JQ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -4.0636153801853405,
          57.52230430623112
        ],
        "type": "Point"
      },
      "UUID": "fe3a87ab-f0d7-4191-86a9-c43a081765ea",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -4.0636153801853405,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T15:20:00.000+0000",
      "latitude": 56.12126642139561,
      "estimatedRestoration": "2022-05-22T17:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5980'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5980",
      "reference": "JT5980",
      "engineerOnSiteTime": "2022-05-22T14:20:00.000+0000",
      "name": "PA24 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PA24 8AD",
        "PA24 8AE",
        "PA31 8NX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -5.08823694704476,
          56.12126642139561
        ],
        "type": "Point"
      },
      "UUID": "f71b1d99-7234-45fa-a23b-f16495215fed",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.08823694704476,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T15:36:00.000+0000",
      "latitude": 56.28805377775656,
      "estimatedRestoration": "2022-05-22T18:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT6066'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT6066",
      "reference": "JT6066",
      "name": "PA35 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PA35 1HG",
        "PA35 1HH",
        "PA35 1HJ",
        "PA35 1HL",
        "PA35 1HN",
        "PA35 1HS",
        "PA35 4AB"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -5.270865890172098,
          56.28805377775656
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-22T16:30:00.000+0000",
      "UUID": "91336330-bb98-424c-8044-813c599bdcfd",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.270865890172098,
      "resolved": false
    }
  ]
}
