{
  "Faults": [
    {
      "latitude": 50.7972933279299,
      "type": "LV",
      "reference": "KT3165",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-05T12:55:00.000+0000",
      "affectedCustomerCount": 7,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "44c508e1-fa35-4cf0-914e-ed324e89f70e",
      "minLongitude": -0.6594,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6539092378039058,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-05T11:42:00.000+0000",
      "estimatedRestoration": "2023-04-05T23:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT3165'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT3165",
      "maxLongitude": -0.652,
      "minLatitude": 50.7963,
      "name": "PO22 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO22 8EP",
        "PO22 8ER",
        "PO22 8EW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.6594,
              50.7998
            ],
            [
              -0.652,
              50.7998
            ],
            [
              -0.652,
              50.7963
            ],
            [
              -0.6594,
              50.7963
            ],
            [
              -0.6594,
              50.7998
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-05T12:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.7998,
      "etrUpdate": true
    },
    {
      "latitude": 50.843492375395115,
      "type": "LV",
      "reference": "KT0658",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-02T15:00:00.000+0000",
      "affectedCustomerCount": 4,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "2ebf3c98-d909-4b79-91cb-1e20190020b6",
      "minLongitude": -1.1937,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.1906680441493425,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-05T17:18:00.000+0000",
      "estimatedRestoration": "2023-04-05T17:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT0658'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT0658",
      "maxLongitude": -1.1846,
      "minLatitude": 50.8414,
      "name": "PO14 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO14 1BJ",
        "PO14 1DJ",
        "PO14 1ET",
        "PO14 1EX",
        "PO14 1NL"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.1937,
              50.8457
            ],
            [
              -1.1846,
              50.8457
            ],
            [
              -1.1846,
              50.8414
            ],
            [
              -1.1937,
              50.8414
            ],
            [
              -1.1937,
              50.8457
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8457,
      "etrUpdate": true
    },
    {
      "latitude": 58.085503085886835,
      "type": "HV",
      "reference": "KT3234",
      "etaUpdate": true,
      "affectedCustomerCount": 28,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "c20d7780-686b-4854-8eeb-724372112ad9",
      "minLongitude": -6.6083,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -6.5342999913108795,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-05T12:41:00.000+0000",
      "estimatedRestoration": "2023-04-05T18:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT3234'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT3234",
      "maxLongitude": -6.4941,
      "minLatitude": 58.0498,
      "name": "HS2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "HS2 9QA",
        "HS2 9QB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -6.6083,
              58.0996
            ],
            [
              -6.4941,
              58.0996
            ],
            [
              -6.4941,
              58.0498
            ],
            [
              -6.6083,
              58.0498
            ],
            [
              -6.6083,
              58.0996
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-05T13:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 58.0996,
      "etrUpdate": true
    },
    {
      "latitude": 55.91883686398082,
      "type": "HV",
      "reference": "KT3366",
      "etaUpdate": true,
      "affectedCustomerCount": 43,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "b2eaf7bb-af32-4735-b010-1f423b2141f7",
      "minLongitude": -5.3536,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.323356337176602,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-05T11:55:00.000+0000",
      "estimatedRestoration": "2023-04-05T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT3366'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT3366",
      "maxLongitude": -5.2354,
      "minLatitude": 55.8804,
      "name": "PA21 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PA21 2ER",
        "PA21 2ES"
      ],
      "location": {
        "coordinates": [
          [
            [
              -5.3536,
              55.9592
            ],
            [
              -5.2354,
              55.9592
            ],
            [
              -5.2354,
              55.8804
            ],
            [
              -5.3536,
              55.8804
            ],
            [
              -5.3536,
              55.9592
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-05T15:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 55.9592,
      "etrUpdate": true
    },
    {
      "latitude": 57.45578840996302,
      "type": "LV",
      "reference": "KT3350",
      "etaUpdate": true,
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "e59c35be-c194-44fb-9d9e-544478163f9d",
      "minLongitude": -6.3837,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -6.320780977575227,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-05T15:04:00.000+0000",
      "estimatedRestoration": "2023-04-05T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KT3350'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KT3350",
      "maxLongitude": -6.2764,
      "minLatitude": 57.3967,
      "name": "IV51 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "IV51 9NP"
      ],
      "location": {
        "coordinates": [
          [
            [
              -6.3837,
              57.4783
            ],
            [
              -6.2764,
              57.4783
            ],
            [
              -6.2764,
              57.3967
            ],
            [
              -6.3837,
              57.3967
            ],
            [
              -6.3837,
              57.4783
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-05T15:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 57.4783,
      "etrUpdate": true
    }
  ]
}
