{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-26T05:13:00.000+0000",
      "latitude": 51.52566802901566,
      "estimatedRestoration": "2022-08-26T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ1047'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ1047",
      "reference": "JZ1047",
      "maxLongitude": -0.3131,
      "engineerOnSiteTime": "2022-08-26T07:15:00.000+0000",
      "minLatitude": 51.5248,
      "name": "W5 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "W5 1RH",
        "W5 1RJ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.3185,
              51.5262
            ],
            [
              -0.3131,
              51.5262
            ],
            [
              -0.3131,
              51.5248
            ],
            [
              -0.3185,
              51.5248
            ],
            [
              -0.3185,
              51.5262
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-26T07:30:00.000+0000",
      "UUID": "21355af4-377d-451f-be21-d989f7793e82",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -0.3185,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.5262,
      "longitude": -0.314899687045701,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-26T11:01:00.000+0000",
      "latitude": 51.265284201621704,
      "estimatedRestoration": "2022-08-26T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ1201'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ1201",
      "reference": "JZ1201",
      "maxLongitude": -1.0942,
      "engineerOnSiteTime": "2022-08-26T12:20:00.000+0000",
      "minLatitude": 51.2646,
      "name": "RG21 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG21 7RU",
        "RG21 7TF",
        "RG21 7TG",
        "RG21 7TH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0974,
              51.2665
            ],
            [
              -1.0942,
              51.2665
            ],
            [
              -1.0942,
              51.2646
            ],
            [
              -1.0974,
              51.2646
            ],
            [
              -1.0974,
              51.2665
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-26T12:30:00.000+0000",
      "UUID": "fe12cd11-051e-419d-9b38-d62f31943ad3",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.0974,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.2665,
      "longitude": -1.0956665227851423,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-26T12:02:00.000+0000",
      "latitude": 50.747754544650384,
      "estimatedRestoration": "2022-08-26T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ1257'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ1257",
      "reference": "JZ1257",
      "maxLongitude": -1.556,
      "engineerOnSiteTime": "2022-08-26T13:15:00.000+0000",
      "minLatitude": 50.7463,
      "name": "SO41 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO41 8AS",
        "SO41 8AT",
        "SO41 8AU"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.5595,
              50.7485
            ],
            [
              -1.556,
              50.7485
            ],
            [
              -1.556,
              50.7463
            ],
            [
              -1.5595,
              50.7463
            ],
            [
              -1.5595,
              50.7485
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-26T13:30:00.000+0000",
      "UUID": "8c23b70f-c75a-45a2-ae68-46f5ba49bf22",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.5595,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.7485,
      "longitude": -1.5573907548100505,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-26T18:04:00.000+0000",
      "latitude": 51.53816762187116,
      "estimatedRestoration": "2022-08-27T00:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ1489'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ1489",
      "reference": "JZ1489",
      "maxLongitude": -1.072,
      "minLatitude": 51.5337,
      "name": "RG8 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG8 0PL",
        "RG8 0PN"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.1094,
              51.5503
            ],
            [
              -1.072,
              51.5503
            ],
            [
              -1.072,
              51.5337
            ],
            [
              -1.1094,
              51.5337
            ],
            [
              -1.1094,
              51.5503
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "6829f22b-9143-4489-b0df-d67897a8596b",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.1094,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.5503,
      "longitude": -1.0873286206868904,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-26T15:50:00.000+0000",
      "latitude": 50.92406889627714,
      "estimatedRestoration": "2022-08-27T03:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ1408'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ1408",
      "reference": "JZ1408",
      "maxLongitude": -1.3609,
      "engineerOnSiteTime": "2022-08-26T16:25:00.000+0000",
      "minLatitude": 50.9232,
      "name": "SO18 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO18 4QH",
        "SO18 4QJ",
        "SO18 4ST",
        "SO18 4SW",
        "SO18 4SX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.3657,
              50.9253
            ],
            [
              -1.3609,
              50.9253
            ],
            [
              -1.3609,
              50.9232
            ],
            [
              -1.3657,
              50.9232
            ],
            [
              -1.3657,
              50.9253
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "66df772b-4c70-44b3-a5f1-75794cb84547",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.3657,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.9253,
      "longitude": -1.3624092679436095,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-26T20:33:00.000+0000",
      "latitude": 51.47068208173762,
      "estimatedRestoration": "2022-08-26T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ1517'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ1517",
      "reference": "JZ1517",
      "maxLongitude": -0.8541,
      "engineerOnSiteTime": "2022-08-26T20:00:00.000+0000",
      "minLatitude": 51.4694,
      "name": "RG10 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG10 0AX",
        "RG10 0AZ",
        "RG10 0BB",
        "RG10 0BD",
        "RG10 0BE",
        "RG10 0XS"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.8592,
              51.4728
            ],
            [
              -0.8541,
              51.4728
            ],
            [
              -0.8541,
              51.4694
            ],
            [
              -0.8592,
              51.4694
            ],
            [
              -0.8592,
              51.4728
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-26T20:00:00.000+0000",
      "UUID": "4e5f9bd2-2c90-42ec-99d9-1c119209d856",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -0.8592,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.4728,
      "longitude": -0.8571934608590436,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-26T20:49:00.000+0000",
      "latitude": 51.49957681188806,
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ1569'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ1569",
      "reference": "JZ1569",
      "name": "SN8 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN8 2HS",
        "SN8 2HT",
        "SN8 2HY",
        "SN8 2HZ",
        "SN8 2JF",
        "SN8 2JP",
        "SN8 2JS",
        "SN8 2LQ",
        "SN8 2NF"
      ],
      "location": {
        "coordinates": [
          -1.5977924069739378,
          51.49957681188806
        ],
        "type": "Point"
      },
      "UUID": "96d4ede5-aa9c-4c7d-8cda-6a2b0bab2601",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.5977924069739378,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-26T18:39:00.000+0000",
      "latitude": 56.39659480106834,
      "estimatedRestoration": "2022-08-26T21:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ1462'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ1462",
      "reference": "JZ1462",
      "maxLongitude": -3.4318,
      "minLatitude": 56.3952,
      "name": "PH1 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PH1 5AB",
        "PH1 5NJ",
        "PH1 5NX",
        "PH1 5PE",
        "PH1 5QA",
        "PH1 5QB",
        "PH1 5QJ",
        "PH1 5QS",
        "PH1 5QT",
        "PH1 5QU"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.4403,
              56.3978
            ],
            [
              -3.4318,
              56.3978
            ],
            [
              -3.4318,
              56.3952
            ],
            [
              -3.4403,
              56.3952
            ],
            [
              -3.4403,
              56.3978
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-26T19:30:00.000+0000",
      "UUID": "13e47e3c-db67-4d35-a8ca-cec97bed337a",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -3.4403,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 56.3978,
      "longitude": -3.4370330285761628,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-26T19:48:00.000+0000",
      "latitude": 57.56628815170552,
      "estimatedRestoration": "2022-08-26T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ1568'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ1568",
      "reference": "JZ1568",
      "maxLongitude": -3.4067,
      "minLatitude": 57.5358,
      "name": "IV36 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV36 2RP",
        "IV36 2RW",
        "IV36 2SA"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.5328,
              57.591
            ],
            [
              -3.4067,
              57.591
            ],
            [
              -3.4067,
              57.5358
            ],
            [
              -3.5328,
              57.5358
            ],
            [
              -3.5328,
              57.591
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-26T20:30:00.000+0000",
      "UUID": "dd5642a9-8aad-43e0-a72f-8706db29a83a",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -3.5328,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 57.591,
      "longitude": -3.4839101110721766,
      "resolved": false
    }
  ]
}
